### ISSUE TITLE
No validation in VS Code

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/quarkus-ls#1000]
In VS Code Quarkus, there is no error markers on bad code.

For instance:

class:
```java
package com.github.datho7561;

public class MyObject {
	public int getValue() {
		return 12;
	}
}
```

template:
```qute-html
{@com.github.datho7561.MyObject myObject}
{myObject.getBalue()}
```

**Expected**: `getBalue()` is marked as an error, since the method name is misspelled.
**Actual**: no error markers anywhere

If I go in the Qute language server trace, the `textDocument/publishDiagnostics` messages all have `diagnostics` set to `[]`.

**Comment by angelozerr** [comment]
That's strange it works for me.

Perhaps your project has not finished to load? If you wait for some times, do you see the error?

**Comment by datho7561** [comment]
I get completion for methods and fields, but I get empty validation responses.

**Comment by angelozerr** [comment]
Could you share your project please.

**Comment by datho7561** [comment]
I can reproduce the issue in quarkus-renarde-todo. Open any template and add this at the beginning:

```qute-html
{@model.User user}
{user.pants}
```

**Comment by angelozerr** [comment]
It works for me:

![image](https://github.com/user-attachments/assets/b2e25cff-214d-4ed0-8680-c0913c3e9a1e)

**Comment by datho7561** [comment]
I forgot to set `"qute.validation.enabled": true`, my bad, I forgot it wasn't on my default. Perhaps we should enable it by default?

**Comment by datho7561** [comment]
There are still false positives in https://github.com/FroMage/quarkus-renarde-todo, which is why we didn't enable it by default.

**Comment by angelozerr** [comment]
> I forgot to set "qute.validation.enabled": true, my bad, I forgot it wasn't on my default. Perhaps we should enable it by default?

Wow I have noticed that, indeed we should se to true by default.

**Comment by angelozerr** [comment]
> There are still false positives in https://github.com/FroMage/quarkus-renarde-todo, which is why we didn't enable it by default.

Which false positive error? Could you create issues please.
