### ISSUE TITLE
Duplicate completion options for ConfigProperty

### ISSUE THREAD

**Issue by xorye** [redhat-developer/quarkus-ls#101]
There are duplicate completion items for ConfigProperty when changing the default value.

To reproduce, continuously change the default value for a ConfigProperty, save the file, and check the list of completions in application.properties:

![Gif showing the bug](https://raw.githubusercontent.com/xorye/gifs/master/new_issues/change_default.gif?token=AE3CR5JZ2S75M5TJE7UESVK5SIWCS)

This issue is a bit difficult to reproduce, I find that sometimes I get duplicates, sometimes I don't.

I find that duplicates are more likely to happen if you do not provide quotations (") for the default value, like I am doing in the gif.

**Comment by angelozerr** [comment]
I think it's a synchronized problem. I will try to write tests to reproduce it and fix it.
