### ISSUE TITLE
Change QuarkusProjectInfo with ReadOnlyQuarkusProjectInfo

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/quarkus-ls#102]
In Quarkus LS, all services (completion, hover, etc) works with the QuarkusProjectInfo whih returns a lits of Quarkus properties. The QuarkusProjectInfo is used in JDL LS and Quarkus LS side to communicate and defines a getter/setter for Quarkus properties

In Quarkus LS side:

 * the Quarkus properties setter should not visible because it's just a read only access for Quarkus properties
 * the QuarkusProjectInfo on Quarkus LS side should provide method like 

`public ExtendedConfigDescriptionBuildItem getProperty(String propertyName) {` 

instead of using utility class `QuarkusPropertiesUtils#getProperty(String propertyName, QuarkusProjectInfo  info)`.

It could define another method like 

`QuarkusProjectInfo#getEnumItems(String propertyName)` this method will be interesting to implement https://github.com/redhat-developer/quarkus-ls/issues/69 to provide a smarter completion/validator for property value (like logging Level).

This issue is to replace QuarkusProjectInfo in all services with ReadOnlyQuarkusProjectInfo (built by QuarkusProjectInfo received from JDL LS) to clean code from all services.

**Comment by jeffmaury** [comment]
read only is to 80s. Should be Immutable.... 😄

**Comment by angelozerr** [comment]
I agree with you @jeffmaury the read only is not very good.

We should find a better name like:

 * ImmutableQuarkusProjectInfo ?
 * QuarkusProjectInfoWrapper ?
 * other?

**Comment by jeffmaury** [comment]
Is this one still relevant after the MicroProfile refactoring ?

**Comment by fbricon** [comment]
Nope. Closing
