### ISSUE TITLE
Add support for YAML configuration files

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/quarkus-ls#112]
Quarkus have the intention to support YAML configuration waith an `application.yaml` file. See [Add support for YAML configuration files](https://github.com/quarkusio/quarkus/issues/3904) issue.

We have 2 choices to support this feature:

 * implements our own YAML parser (like camel language server does that) but it's not perfect according @apupier .
 * consume yaml language server.

I create an issue about consuming [this yaml language server issue](https://github.com/redhat-developer/yaml-language-server/issues/190) and it seems that it's possible to contribute to the YAML Schema.

@JPinkney gived me a great explanation [how to contibute with YAML schema](https://github.com/redhat-developer/yaml-language-server/issues/190#issuecomment-540044607).

My idea is to generate a YAML schema from our Quarkus properties. If @fbricon and @xorye are OK I would like to explore this idea (for our next sprint).

**Comment by Ginxo** [comment]
@angelozerr any progress here? thanks for the effort

**Comment by angelozerr** [comment]
@Ginxo nothing has been done. We need study how we could manage YAML with or without existing YAML language server (with or without vscode-yaml)

Is it a feature which is a lot used in Quarkus application?

**Comment by angelozerr** [comment]
@Ginxo it seems Quarkus doesn't provide this feature now https://github.com/quarkusio/quarkus/issues/3904#issuecomment-559139151 

We wait for that to start to investigate something with yaml.

**Comment by angelozerr** [comment]
@fbricon in few hours I have supported Quarkus application.yaml with vscode-yaml, by following the explanation [how to contibute with YAML schema](https://github.com/redhat-developer/yaml-language-server/issues/190#issuecomment-540044607) I have done copied/pasted https://github.com/Azure/vscode-kubernetes-tools/blob/127ec070c8dabd56901ce13ff81bd6f561e4f087/src/yaml-support/yaml-schema.ts#L24 and adapt it for Quarkus.

All is done in TypeScript, the basic idea is to:

 * get properties from JDT LS (with workspave.java.command)
 * convert properties into JSON Schema
 * use vscode-yaml registerContribution to bind the application.yaml file with the JSON Schema

You can find my work in the branch https://github.com/angelozerr/vscode-quarkus/tree/yaml (code is very ugly).

Here a demo:

![QuarkusYamlDemo](https://user-images.githubusercontent.com/1932211/71767824-c045bf00-2f10-11ea-94f6-199c28d3c0fa.gif)

It misses some features like type (string , enum) but I wanted just to test the idea.

It works but there are some limitations compare to application.properties like:

 * vscode-yaml doesn't give the capability to customize definition (to jump to java field, method where property is declared).
 * vscode-yaml doesn't give the capability to customize code actions (we loose our code actions with 'did you mean?' , 'ignore this property', etc.

It's my first feeling, perhaps I miss some features. In other words here pros/cons to be based on vscode-yaml

* pros
  * very easy to implement (no need to implement yaml parser, no need to implement apply completion, no need to implement format, etc).

* cons:
  * mapped property cannot be managed with a JSON Schema.
  * loose features like code actions and definitions.
