### ISSUE TITLE
QuarkusPropertiesScope is confusing

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/quarkus-ls#116]
QuarkusPropertiesScope defines two values: `sources` and `classpath`. But it turns out that classpath value means parsing both classpath and sources files. So either the documentation should make it clear or we should rename it.

**Comment by fbricon** [comment]
Agreed. Should be `sources` and `dependencies`

**Comment by angelozerr** [comment]
> Agreed. Should be sources and dependencies

What do you think about that?

**Comment by jeffmaury** [comment]
I think the proposed names are still confusing. I would rather have `sources` and `sourcesAndDependencies`

**Comment by angelozerr** [comment]
@fbricon are you OK with the @jeffmaury suggestion?

**Comment by angelozerr** [comment]
An another idea is to have `sources` and `dependencies` and fill scope with the both in the case of sourceAndDependencies

**Comment by fbricon** [comment]
Yes composition is better

**Comment by angelozerr** [comment]
Done in https://github.com/redhat-developer/quarkus-ls/pull/159
