### ISSUE TITLE
Provide default method when extending QuarkusLanguageClientAPI

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/quarkus-ls#120]
It would be good for implementers that when a new method is added to the `QuarkusLanguageClientAPI`, it should be provided as a default method.
Ex: an new interface `QuarkusPropertyDefinitionProvider` has been added that defines a single `getPropertyDefinition` method, it could have been defaulted to `CompletableFuture.completedFuture(null)`

**Comment by angelozerr** [comment]
I agree with you, could you create a PR please.
