### ISSUE TITLE
Duplicate completion options in Gradle projects

### ISSUE THREAD

**Issue by xorye** [redhat-developer/quarkus-ls#137]
There are duplicate completion items for  `quarkus.application.name` and `quarkus.application.version`.

The duplication items show up consistently.

![image](https://user-images.githubusercontent.com/20326645/68128251-60697280-fee5-11e9-90ae-fed6033bccab.png)

To reproduce this bug:

* Clone https://github.com/xorye/sample-quarkus-gradle-project
* Install latest Quarkus Tools for VS Code: https://marketplace.visualstudio.com/items?itemName=redhat.vscode-quarkus
* Open src/main/resources/application.properties
* Invoke completion (Ctrl + Space)

**Comment by angelozerr** [comment]
@xorye if you see detail of duplicated completion item, is belong to the same extension name (quarkus-core)?

If you go to the definition for duplicated property is it the same class ?

**Comment by xorye** [comment]
Yes, they have the same extension name.
But once I have one of them in the application.properties file, the duplicate completion item goes away.
Here's a gif:
![Duplicate property Gradle gif](https://raw.githubusercontent.com/xorye/gifs/master/new_issues/dup_gradle.gif?token=AE3CR5PR3LPTITIGH6YYIGS5ZGJKK)


> If you go to the definition for duplicated property is it the same class ?

I'm not sure how to test this at the moment. Is there a way to go to definition without Ctrl+click on the property once the property is in the actual file?

**Comment by angelozerr** [comment]
@xorye don't loose your time with this issue. I will try to reproduce it (today or tomorrow) . Hope I could reproduce it to understand the problem.

**Comment by angelozerr** [comment]
Problem comes from that Eclipse Java classpath contains the `quarkus-core-deployment.jar`

![image](https://user-images.githubusercontent.com/1932211/68196486-0afe9580-ffb9-11e9-981d-2c9c6c07bdcd.png)

When collect of Quarkus properties have processed, we build a new classpath which adds the `quarkus-core-deployment.jar` too, in other words the classpath which is used to process the search have 2 `quarkus-core-deployment.jar` which explains the duplicate Quarkus properties.

**Comment by fbricon** [comment]
The project uses gradle 5.5 which doesn't separates main and test classpaths. Everything, including test dependencies are available in the main classpath. You can change the gradle version to 5.6.4 in gradle/wrapper/gradle-wrapper.properties and update the project configuration.
