### ISSUE TITLE
Default profile completion provides invalid value  

### ISSUE THREAD

**Issue by xorye** [redhat-developer/quarkus-ls#160]
![image](https://user-images.githubusercontent.com/20326645/70549528-5d941a00-1b42-11ea-9406-98f44e895b4b.png)

In the image above, `quarkus` should not be one of the completion options.

To reproduce this error:

1. place the cursor before the property key:
```
|quarkus.http.port=8080
```
2. Type '%'. This provides the default profile completion options. 

3. 'quarkus' appears as one of the completion options

**Comment by xorye** [comment]
This issue does not happen after https://github.com/redhat-developer/quarkus-ls/pull/266 was merged.

This new condition from the PR: https://github.com/redhat-developer/quarkus-ls/pull/266/files#diff-b476d6ae3dee42678361e37473a02deaR270 fixes this issue because the profile completion option is not provided if it matches the current key's profile.

The reason why `quarkus` is one of the profile completion options in this case is because when `%` is typed, the property becomes `%quarkus.http.port=8080` and therefore the code considers `quarkus` to be a profile

**Comment by angelozerr** [comment]
That's nice :) So we can close this issue?

**Comment by xorye** [comment]
Yes, closing
