### ISSUE TITLE
Activate travis

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/quarkus-ls#17]
Activate travis to build JDT LS Extension and Quarkus LS. Quarkus LS provides test for completion, it should be good to activate travis and add the status of travis in the README.

@fbricon is there any chance that you work on this issue?

**Comment by fbricon** [comment]
Travis build is activated (see badge in readme), but for now, the jdt.ls extension tests are disabled as they fail to run for some reason I need to figure out.
