### ISSUE TITLE
Hovering over equals sign is being treated as hovering over the property key

### ISSUE THREAD

**Issue by xorye** [redhat-developer/quarkus-ls#172]
![image](https://user-images.githubusercontent.com/20326645/71377909-05becf80-2594-11ea-9d26-b48e4acbfdcc.png)

This is happening because when hovering over the equals sign, the `document.findNodeAt()` call [here](https://github.com/redhat-developer/quarkus-ls/blob/4602b0bbcdee34367b84d33ff75759ec10a1c1d7/microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/services/MicroProfileHover.java#L62) returns the node for the property key, not the node for the equals (assign) sign.

**Comment by fbricon** [comment]
Please also replace QuarkusHover with MicroProfileHover in https://github.com/redhat-developer/quarkus-ls/blob/4602b0bbcdee34367b84d33ff75759ec10a1c1d7/microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/services/MicroProfileHover.java#L65
