### ISSUE TITLE
Refactor unit tests so that they can be reused for validating alternate IJDTUtils implementations

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/quarkus-ls#187]
As jbosstools-quarkus implements IJDTUtils based on JDT and not JDT.LS it would be good if we can reuse the existing unit tests for validating this alternate IJDTUtils implementation

**Comment by fbricon** [comment]
@jeffmaury any short term plans for this one?

**Comment by jeffmaury** [comment]
No found the issues that tests are fragments and it causes issues when trying to reuse and didn't managed to find time to go next
