### ISSUE TITLE
Missing mp-rest properties

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/quarkus-ls#189]
According to the [microprofile rest client spec](https://download.eclipse.org/microprofile/microprofile-rest-client-1.3.3/microprofile-rest-client-1.3.3.pdf), the following properties should be supported: 

> The values of the following properties will be provided via MicroProfile Config:
• com.mycompany.remoteServices.MyServiceClient/mp-rest/url: The base URL to use for this service,
the equivalent of the baseUrl method. This property (or */mp-rest/uri) is considered required,
however implementations may have other ways to define these URLs/URIs.
• com.mycompany.remoteServices.MyServiceClient/mp-rest/uri: The base URI to use for this service,
the equivalent of the baseUri method. This property (or */mp-rest/url) is considered required,
however implementations may have other ways to define these URLs/URIs. This property will
override any baseUri value specified in the @RegisterRestClient annotation.
• com.mycompany.remoteServices.MyServiceClient/mp-rest/scope: The fully qualified classname to a
CDI scope to use for injection, defaults to javax.enterprise.context.Dependent as mentioned
above.
• com.mycompany.remoteServices.MyServiceClient/mp-rest/providers: A comma separated list of
fully-qualified provider classnames to include in the client, the equivalent of the register
method or the @RegisterProvider annotation.
• com.mycompany.remoteServices.MyServiceClient/mprest/providers/com.mycompany.MyProvider/priority will override the priority of the provider for
this interface.
• com.mycompany.remoteServices.MyServiceClient/mp-rest/connectTimeout: Timeout specified in
milliseconds to wait to connect to the remote endpoint.
• com.mycompany.remoteServices.MyServiceClient/mp-rest/readTimeout: Timeout specified in
milliseconds to wait for a response from the remote endpoint.
Implementations may support other custom properties registered in similar fashions or other ways.
The url property must resolve to a value that can be parsed by the URL converter required by the
MicroProfile Config spec. Likewise, the uri property must resolve to a value that can be parsed by
the URI converter. If both the url and uri properties are declared, then the uri property will take
precedence.
The providers property is not aggregated, the value will be read from the highest property
17
ConfigSource.

right now we only have 3 of those.

**Comment by angelozerr** [comment]
@jclingan I would lile to manage the last MP Rest property

```
com.mycompany.remoteServices.MyServiceClient/mprest/providers/com.mycompany.MyProvider/priority will override the priority of the provider for
this interface.
```
I mean 

`<service-class>/mp-rest/providers/<provider-class>/priority`

My question is about what is the allowed value for `<provider-class>` ?

 * all available providers (all classes which implements ClientResponseFilter, ClientRequestFilter, MessageBodyReader, MessageBodyWriter, ParamConverter, ReaderInterceptor, ResponseExceptionMapper)? If it that, I'm little afraid with performance to collect those providers.

 * only provider which are declared with @RegisterProvider for the given <service-class> ? If it that I have a start of work which could manage that.

If the answer is all available providers, I think I will manage that with simple mean, I will use our mapped property {*} to manage this property and you will need to fill at hand the provider class value.

Thanks for your help.

**Comment by angelozerr** [comment]
> If the answer is all available providers, I think I will manage that with simple mean, I will use our mapped property {*} to manage this property and you will need to fill at hand the provider class value.

@fbricon  I tried to use the Quarkus mapped priority  `${mp.register.rest.client.class}/mp-rest/providers/{*}/priority` but the {*} must not use `.` (or must be escaped with quote), in another words we cannot use mapped property.

In other words, managing `${mp.register.rest.client.class}/mp-rest/providers/{*}/priority`  is very hard. To manage correctly we must manage the capability to open completion for providers classes. We could use this capability for mapped property too (for package completion with log mapped property).

I think we could close this issue and create an another issues to manage the hard property `${mp.register.rest.client.class}/mp-rest/providers/{*}/priority` 

@fbricon what do you think?
