### ISSUE TITLE
ConfigProperty name hover should take application.yaml into consideration

### ISSUE THREAD

**Issue by xorye** [redhat-developer/quarkus-ls#196]
This feature https://github.com/redhat-developer/quarkus-ls/pull/151 only checks for config values in `application.properties`.

It would be nice if it could also check `application.yaml`.

**Comment by angelozerr** [comment]
Indeed,and we need too get the http.server.port too from yaml file

**Comment by angelozerr** [comment]
Fixed with https://github.com/redhat-developer/quarkus-ls/pull/220
