### ISSUE TITLE
Value from Java enum are not correct

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/quarkus-ls#198]
Today value from Java enum are used in the application.properties file 

For instance we have:

`quarkus.log.console.async.overflow = BLOCK
`
where `BLOCK` is the Java enum name.

But we should have (see discussion at https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/What.20is.20the.20case.20sensitive.20rule.20for.20value.20property.20with.20enum)

`quarkus.log.console.async.overflow = block 
`
We must study the rule of convert of Java enum value (see https://quarkus.io/guides/writing-extensions#enhanced-conversion)

It seems that `BLOCK` and `block` are correct for `quarkus.log.console.async.overflow`

We have the same problem with `quarkus.datasource.transaction-isolation-level`. Our allowed value are for instance `REPEATABLE_READ` although documentation 
See https://quarkus.io/guides/all-config#quarkus-agroal_quarkus.datasource.transaction-isolation-level says `repeatable-read`

**Comment by fbricon** [comment]
Same problem with quarkus.hibernate-search.elasticsearch.index-defaults.lifecycle.required-status
Proposed values are GREEN, YELLOW, RED instead of green, yellow, red.

**Comment by angelozerr** [comment]
After reading Quarkus documentation https://quarkus.io/guides/writing-extensions#enhanced-conversion the Quarkus Java enumeration use hypernate converter by default:


Java enum | Canonical equivalent
-- | --
DISCARD | discard
READ_UNCOMMITTED | read-uncommitted

But this behavior can be changed if you set a converter with `@ConvertWith` annotation. It can be complex to manage this usecase.

In other words I think we should manage the default Quarkus behaviour, in other words, I think we should convert enum values with hypenate (like we done for property name according the @ConfigItem value). We could do this hypenate convertion only for Java enum which is used by Quarkus properties.

@fbricon have you agree with that?

After the question is what about MicroProfile properties? For the moment I have not seen usecase with MicroProfile and Java enum. @jclingan what do you think if we convert Java enum with hypenate rule?

Perhaps you don't like this idea, so perhaps the solution is to check if the project is a Quarkus project (in this case hypenate rule is used), otherwise if it's a just a MicroProfile project without Quarkus, there is no convertion to do for enum.

@jclingan @fbricon what do you think about those ideas?

**Comment by angelozerr** [comment]
After playing with Java enum with Quarkus and MicroProfile, here the conclusion (for default behaviour):

 * MicroProfile with (ConfigProperty annotation) use the real Java enumeration name.
 * Quarkus (with ConfigIRoot annotation) uses kebab-case (hyphenate with '-'), but accept too real java enumeration name.

It means that this kebab-case must be done on MicroProfile LS side and not on JDT LS side because a given Java enumeration can be used on MicroProfile ConfigProperty and Quarkus ConfigRoot both.
