### ISSUE TITLE
Support ConfigProperties for 1.2

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/quarkus-ls#200]
We should change the strategy for generate properties with ConfigProperties on JDT LS for 1.2 https://github.com/quarkusio/quarkus/wiki/Migration-Guide-1.2#configproperties

@fbricon do you think we should support all version of Quarkus?

**Comment by fbricon** [comment]
It might not be too difficult to support both strategies

**Comment by angelozerr** [comment]
> It might not be too difficult to support both strategies

No I think it's not hard to support the 2 strategies (except for configuring it with `quarkus.arc.config-properties-default-naming-strategy=verbatim` because it means when user change this property, all properties name should be recomputed (like a classpath changed).

My question was about the default behaviour. Today our default behaviour is verbatim, since 1.2, default behaviour is kebab-case

**Comment by fbricon** [comment]
we should be able to detect which version of quarkus is on the classpath and then apply the matching strategy automatically
