### ISSUE TITLE
Validate application.properties: required properties

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/quarkus-ls#21]
Validate application.properties:

 * required Quarkus properties. See case 1 in https://quarkus.io/guides/application-configuration-guide#injecting-configuration-value. 

Add CodeAction to add required properties.

**Comment by xorye** [comment]
@angelozerr is this issue only for @ConfigProperty?

If this issue is also for @ConfigRoot, @ConfigItem etc, I will investigate more about the meaning of "required" for @ConfigRoot, @ConfigItem etc.

**Comment by angelozerr** [comment]
The original issue was about required for any annotation but we can split this issue in two issues if you wish. Please rename this issue  (by adding for ConfigProperty) and create a new issue for ConfigRoot.

But it means ExtendedConfigDescriptionBuildItem should return the annotation origin of the Quarkus property computing,no?

**Comment by xorye** [comment]
Maybe it might be better to depend on `required`, since it would take care of required for any annotation. I will investigate more

**Comment by angelozerr** [comment]
> Maybe it might be better to depend on required, since it would take care of required for any annotation. I will investigate more

Yes it was my idea. You need to fill th erequired info from the JDTQuarkusManager. If you need help, please tell me

**Comment by angelozerr** [comment]
Fixed with https://github.com/redhat-developer/quarkus-ls/pull/91
