### ISSUE TITLE
CodeAction to Generate Open API Annotations

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/quarkus-ls#239]
This CodeAction to `Generate Open API Annotations `feature is supported by the IBM MicroProfile LS https://github.com/MicroShed/microprofile-language-server/blob/517056559d82244355b51365d6617caf5b36be1f/src/main/java/com/microprofile/lsp/internal/helper/SourceAssistHelper.java

The idea is to provide a CodeAction `Generate Open API Annotations ` with `CodeActionKind.Source` to generate Open API annotations. The current implementation generates the @Operation annotation for each methods of the class (see https://github.com/MicroShed/microprofile-language-server/blob/517056559d82244355b51365d6617caf5b36be1f/src/main/java/com/microprofile/lsp/internal/GenerateOpenAPIAnnotations.java#L78).

**Comment by ericglau** [comment]
@angelozerr Let me know if you would like our team to help take a look at this one (if you haven't started working on it yet).

**Comment by angelozerr** [comment]
@ericglau it should be very nice, but please wait for that I implement code action with extension point in https://github.com/redhat-developer/quarkus-ls/issues/236 I'm working on this issue.

The idea is to :

 * provide an extension point to manage extensible code action
 * provide the same idea of JDT LS CodeActionHandler, I mean create changes by using JDT codemanipulation API and transform it to LSP WorkspaceEdit. The idea is to not work directly with WorkspaceEdit but working with DT codemanipulation API. Using DT codemanipulation API is powefull and can manage import (or not) of annotation when an annotation must be insert before a class (the issue of https://github.com/redhat-developer/quarkus-ls/issues/236), canmanage formatting, etc.

I will ping you as soon as I will finish my work.

**Comment by angelozerr** [comment]
@ericglau CodeAction extension point are not merged in master. 

It seems Benson (Ning) will work on this issue and he is aware about this CodeAction extension point.

**Comment by bensonnw** [comment]
@angelozerr Please assign this to me

**Comment by angelozerr** [comment]
@bensonnw please write test for your CodeAction support. You have a sample at https://github.com/redhat-developer/quarkus-ls/blob/master/microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/health/JavaDiagnosticsMicroProfileHealthTest.java#L68

**Comment by angelozerr** [comment]
Fixed by https://github.com/redhat-developer/quarkus-ls/pull/275
