### ISSUE TITLE
Manage static properties with JSON files

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/quarkus-ls#247]
Today when there are static properties we hard coded that in JDT LS side. See sample with MicroProfile Metrics https://github.com/redhat-developer/quarkus-ls/blob/46a8164a2456e7f9c4ca8f4dd5776884f7be3f66/microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/metrics/properties/MicroProfileMetricsProvider.java#L47

It should be more safe if we could describe those properties in a JSON files like this:

```json
{
	"properties": [
		{
			"type": "java.lang.String",
			"name": "mp.metrics.tags",
			"description": "List of tag values.\r\nTag values set through `mp.metrics.tags` MUST escape equal symbols `=` and commas `,` with a backslash `\\`.",
		},
		{
...
		}
	],
	"hints": [
	]
}
]
```

The description is written with markdown syntax. If the LSP client cannot support Markdown, we could use [commonmark-java](https://github.com/atlassian/commonmark-java#parse-and-render-to-html) to convert the markdown description into plaintext:

```java
Parser parser = Parser.builder().build();
Node document = parser.parse("This is *Sparta*");
TextContentRenderer renderer = TextContentRenderer.builder().build(); 
String plaintext = renderer.render(document);
System.out.println( plaintext ); 
```

This JSON files could be loaded in the `MetricsPropertiesProvider` class or an another idea is to improve the existing propertiesProvider extension point to load this JSON fles like this:

```xml
   <extension point="com.redhat.microprofile.jdt.core.propertiesProviders">
      <!-- Properties provider for the MicroProfile Metrics  -->
      <staticProvider when="org.eclipse.microprofile.metrics.MetricID" 
                               resource="/properties/metrics.json" />
   </extension>
```

 * `when `: check if the given class exists in the classpath to return the list of properties
 * `resource`:  file path of the JSON file.

**Comment by fbricon** [comment]
This would probably be more flexible in the long term
```
<staticProvider resource="foo">
   <when>
         <typeOnClasspath>org.eclipse.microprofile.metrics.MetricID</typeOnClasspath>
         ...
   </when>
</staticProvider>
```

**Comment by fbricon** [comment]
can also add `<and>` / `<or>` conditions

**Comment by angelozerr** [comment]
Indeed, it should be better, I think we should use `enabledWhen `instead of `when`. I already did that.

 * for extension point schema, see https://github.com/eclipse/eclipse.platform.text/blob/707a5c2da6ad19068610194f57a026761e92abe2/org.eclipse.ui.genericeditor/schema/foldingReconcilers.exsd#L55

 * after that you load Eclipse Core Expression like this https://github.com/eclipse/eclipse.platform.text/blob/707a5c2da6ad19068610194f57a026761e92abe2/org.eclipse.ui.genericeditor/src/org/eclipse/ui/internal/genericeditor/GenericContentTypeRelatedExtension.java#L70 where extension point registry is loaded

 * the expression evulation is done like this https://github.com/eclipse/eclipse.platform.text/blob/707a5c2da6ad19068610194f57a026761e92abe2/org.eclipse.ui.genericeditor/src/org/eclipse/ui/internal/genericeditor/GenericContentTypeRelatedExtension.java#L94

**Comment by angelozerr** [comment]
This issue is done by https://github.com/redhat-developer/quarkus-ls/pull/267 but it misses extension point.

**Comment by angelozerr** [comment]
Today we can declare statix properties in JSON files. It misses the extension point part.  Move to https://github.com/eclipse/lsp4mp/issues/44
