### ISSUE TITLE
Quarkus Completion support for property expressions

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/quarkus-ls#248]
See https://quarkus.io/guides/config#using-property-expressions

According the comments https://github.com/quarkusio/quarkus/issues/7848#issuecomment-598749800 we can write:

```properties
host.gateway=http://localhost:21301/fedahub-gw
%dev.host.gateway=http://192.168.3.2:21301/fedahub-gw

c2b.register.url.validation=${host.gateway}/register/validation
c2b.register.url.confirmation=${host.gateway}/register/confirmation
b2c.url.queue.timeout=${host.gateway}/b2c/queuetimeout
b2c.url.result=${host.gateway}/b2c/result
b2b.url.queue.timeout=${host.gateway}/b2b/queuetimeout
b2b.url.result=${host.gateway}/b2b/result
stk.url.callback=${host.gateway}/stk/callback
balance.url.queue.timeout=${host.gateway}/accountbalance/queuetimeout
balance.url.result=${host.gateway}/accountbalance/result
status.url.queue.timeout=${host.gateway}/transactionstatus/queuetimeout
status.url.result=${host.gateway}/transactionstatus/result
reversal.url.queue.timeout=${host.gateway}/reversal/queuetimeout
reversal.url.result=${host.gateway}/reversal/result
```

An idea is to manage completion on value after $:

`c2b.register.url.validation=${ |`

should return `${host.gateway}`

It seems that `${host.gateway}` comes from too with profile value. I mean %dev.host.gateway=http://192.168.3.2:21301/fedahub-gw should return on value `${host.gateway}` and not `${%dev.host.gateway}` (not sure with that, we must check that)

**Comment by dwamara** [comment]
@angelozerr It does work with profiles too, I tested it and it worked perfectly. The placeholder should not have the profile in it in the place where it has to be replaced.

**Comment by angelozerr** [comment]
Thanks @dwamara for your feedback.

**Comment by angelozerr** [comment]
@datho7561 we need to implement https://github.com/redhat-developer/quarkus-ls/issues/336 before this issue.

**Comment by datho7561** [comment]
Please see (this lsp4mp PR)[https://github.com/eclipse/lsp4mp/pull/13], which aims to implement property expression completion in the microprofile language server.

**Comment by angelozerr** [comment]
Fixed with https://github.com/eclipse/lsp4mp/pull/13
