### ISSUE TITLE
Validate application.properties: unknown properties

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/quarkus-ls#26]
Validate application.properties

 * Quarkus properties which doesn't exists.

before doing this issue, the issue https://github.com/redhat-developer/quarkus-ls/issues/9 should be fixed to collect all properties (from JAR and sources).

Pay attention with map quarkus properties which looks like:

`quarkus.mymap."any.value" = `. The cache stores `quarkus.mymap.{*}` as key map and not  `quarkus.mymap."any.value"`

**Comment by fbricon** [comment]
You might use application.properties to define non-quarkus properties so I'm not sure about this one. 
Might only need to validate the quarkus namespace

**Comment by angelozerr** [comment]
> You might use application.properties to define non-quarkus properties so I'm not sure about this one.

Indeed perhaps it's a bad idea.

> Might only need to validate the quarkus namespace

If you are using @ConfigProperty there are not quarkus namespace (not managed for the moment, I must do that in https://github.com/redhat-developer/quarkus-ls/issues/30)

More it seems that there are some Quarkus properties which hard coded, see 
https://github.com/redhat-developer/quarkus-ls/issues/29

I think more and more it's a bad idea or perhaps set the unknown properties as warning?
