### ISSUE TITLE
Filter for Java (server) snippet 

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/quarkus-ls#265]
Once https://github.com/redhat-developer/quarkus-ls/pull/251 will be merged, we need to improve Java snippets completion:

* `filter Java snippets` according to some conditions like:
  * if `project has some dependency ` (ex : Open API @Operation snippet should be shown only if the project have the openapi dependency)
  * `where completion has been triggered` (ex : Open API @Operation snippet should be shown only if completion is triggered before a class, etc)

To do that, we must delegate those 2 features on JDT LS side. We could have a `microprofile/java/completion/resolveCompletionContext` JDT LS command which:

 * resolve condition (ex have this dependency? is completion is triggered before class, etc)

The idea is when completion is opened and snippets requires condition and compute of context  , it should call one time the resolveCompletionContext which should resolve condition and compute of context.

**Comment by angelozerr** [comment]
@rzgry here the idea that I have in my mind to manage filter for snippet. Takes a sample with Metrics snippet:

The idea is to write a context liek this:

```json
"context": {
    	"target": ["method", "field", "parameter", "annotation_type"],
    	"dependency": "microprofile-metrics"
    }
```
in other words:

```json
"@Metric": {
    "prefix": [
      "@Metric"
    ],
    "body": [
      "@Metric(",
      "\tname = \"${1:name}\",",
      "\tdescription = \"${2:description}\"",
      ")"
    ],
    "description": "An annotation that contains the metadata information when requesting a metric to be injected or produced. This annotation can be used on fields of type Meter, Timer, Counter, and Histogram. For Gauge, the @Metric annotation can only be used on producer methods/fields.",
    "context": {
    	"target": ["method", "field", "parameter", "annotation_type"],
    	"dependency": "microprofile-metrics"
    }
  }
```

The context means 

 * `target `: the snippet is shown only when completion is triggered before a method, field, parameter or annotation_type.
 * `dependency` : the snippet is shown only when project has the microprofile-metrics dependency.

@rzgry do you like this idea? Please give me feedback.

If you like it, could you create a PR with the context for mp-* snippets please. Thanks!

**Comment by rzgry** [comment]
Looks good to me. I can make a PR to add context to the existing MicroProfile snippets.
