### ISSUE TITLE
Go to definition for @ConfigProperty bound to parameters

### ISSUE THREAD

**Issue by xorye** [redhat-developer/quarkus-ls#285]
Currently, when a `@ConfigProperty` is bound to a method parameter like so:
```
    @Inject
    public void setMessage(@ConfigProperty(name = "greeting.method.message") String message) {
        this.message = message;
    }

```

Doing "Go to definition" for `greeting.method.message` from an application.properties file brings the user to the `setMessage()`'s location.

It would be better if it would bring the user directly to the `String message`'s location instead.

**Comment by angelozerr** [comment]
To manage this usecase, we need to add `sourceParameter` information in ItemMetadata like this

```json
{
      "sourceType": "..."
      "sourceMethod": "setMessage....",
      "sourceParameter": "message",
    }
```

**Comment by angelozerr** [comment]
Move to https://github.com/eclipse/lsp4mp/issues/91
