### ISSUE TITLE
How to manage properties like quarkus.hibernate-orm.database.generation ?

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/quarkus-ls#29]
The hibernate-orm-resteasy sample project contains an application.properties with hibernate config like

```
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
```

The Quarkus JDT LS extension is not able to manage those properties since it doesn't exists an HibernateORMConfig class for instance.

I suppose that https://github.com/quarkusio/quarkus/blob/master/extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmProcessor.java manage thoses properties without @ConfigRoot annotation. In this case how to manage those properties? By adding hard coded list?

**Comment by fbricon** [comment]
ping @emmanuelbernard

**Comment by angelozerr** [comment]
@fbricon good news, after adding the dependency `quarkus-hibernate-orm-deployment` after teh existing `quarkus-hibernate-orm` dependency :

```
<dependency>
	<groupId>io.quarkus</groupId>
	<artifactId>quarkus-hibernate-orm</artifactId>
</dependency>
<dependency>
	<version>${quarkus.version}</version>
	<groupId>io.quarkus</groupId>
	<artifactId>quarkus-hibernate-orm-deployment</artifactId>
</dependency>

```

it works great:

![image](https://user-images.githubusercontent.com/1932211/63369706-cfbcd500-c380-11e9-96e6-265061e88bc2.png)

It's the same issue than https://github.com/redhat-developer/quarkus-ls/issues/39
