### ISSUE TITLE
Create a new project com.redhat.quarkus.ls

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/quarkus-ls#295]
To fix one point of https://github.com/redhat-developer/quarkus-ls/issues/268, we need to create a new project com.redhat.quarkus.ls which embedds https://github.com/redhat-developer/quarkus-ls/tree/master/microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/quarkus/snippets and https://github.com/redhat-developer/quarkus-ls/tree/master/microprofile.ls/com.redhat.microprofile.ls/src/main/resources/com/redhat/quarkus/snippets . When MicroProfile LS is started we need to add the com.redhat.quarkus.ls JAR in classpath to load with Java SPI Quarkus snippets

**Comment by fbricon** [comment]
Ok so to clarify, what we're aiming for right now is a split of the different bits into distinct microprofile and quarkus areas: So, at the root of this repo, and until the microprofile bits move to the EF, we should have:
- microprofile-ls: the core LS for microprofile
- microprofile-jdt: the JDT-LS extension for microprofile
- quarkus-ls-ext: SPI contributions to microprofile-ls
- quarkus-jdt-ext: JDT-LS extension point contributions to microprofile-jdt

Ultimately, microprofile-* will live in a different repo. This means we'll basically have 4 different independent builds.
quarkus-ls-ext will depend on microprofile-ls artifacts, quarkus-jdt-ext will depend on microprofile-jdt bits

**Comment by angelozerr** [comment]
@rzgry if you need more information, don't hesitate to ask us.

**Comment by rzgry** [comment]
@fbricon So i have a PR that splits `microprofile.ls` into two projects here https://github.com/redhat-developer/quarkus-ls/pull/304. Should I also take a look at splitting the `microprofile.jdt` into two projects? I know right now the jdt is split into separate modules.

**Comment by fbricon** [comment]
This is done in master
