### ISSUE TITLE
Validate application.properties: syntax error

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/quarkus-ls#3]
Validate application.properties:

 * syntax error : ex : key name which have not '=' only if it's not inside a line comment.

Add CodeAction to add the  '='

**Comment by xorye** [comment]
I think things will be easier for me if I added an "EQUAL_SIGN" token in [`PropertiesScannerUtils.java`](https://github.com/redhat-developer/quarkus-ls/blob/master/quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/utils/PropertiesScannerUtils.java). 

What do you think?
