### ISSUE TITLE
Goto Declaration not working in certain conditions

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/quarkus-ls#323]
I have the following content:

```
# Configuration file
# key = value
my.property=jeff

```
where my.property is defined here:

```
package org.acme;

import javax.inject.Inject;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

import org.eclipse.microprofile.config.inject.ConfigProperty;

@Path("/hello")
public class ExampleResource {

    @ConfigProperty(name="my.property")
    public String myProperty;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "hello";
    }
}
```

If I double click on `my` and then F12 (Go to Definition) then it's ok.
If I double click on `property` and then F12 (Go to Definition) then nothing is done.
If I set the cursor inside `property` and then F12 (Go to Definition) then it's ok.
If I set after `y` and then F12 (Go to Definition) then nothing is done.

**Comment by datho7561** [comment]
I can confirm that this is still broken. I'll take a look at it, hopefully it's a simple fix.
