### ISSUE TITLE
Rename `quarkus` prefix settings (used by language server) with `microprofile` 

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/quarkus-ls#325]
Today settings uses `quarkus` as prefix for settings used by language server. It should be renamed with `microprofile`. See 
https://github.com/rzgry/prototype-vscode-microprofile/blob/73fc02276981257b936888b670a0ad8529c2bd93/package.json#L77

The question is about vscode-quarkus, should we remove the settings used by language server?

**Comment by rzgry** [comment]
Also need to update client commands used by the LS. Ex..https://github.com/redhat-developer/quarkus-ls/blob/b410a0a3dbefd667f04d4e60d0d153fbc9fd6950/microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/ls/commons/client/CommandKind.java#L41

**Comment by angelozerr** [comment]
Fixed with https://github.com/eclipse/lsp4mp/pull/51
