### ISSUE TITLE
Validate application.properties: type value

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/quarkus-ls#33]
According the type value (ex : int, boolean, other?), validation should be done:

Ex :

 * with quarkus.datasource.enable-metrics which is a boolean

`quarkus.datasource.enable-metrics = XXXX
`

XXXX should be marked as error

 * with `quarkus.datasource.max-size` which is an int

`quarkus.datasource.max-size = XXXX
`

XXXX should be marked as error

**Comment by fbricon** [comment]
It might not work, if the values are injected at build time, by Maven/Gradle, eg: ${value.from.pom}

**Comment by fbricon** [comment]
Keepo in mind some properties can be injected at build time ${something}, so it should not be validated
