### ISSUE TITLE
Definition support for property expressions

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/quarkus-ls#333]
See https://quarkus.io/guides/config#using-property-expressions

```properties
host.gateway=http://localhost:21301/fedahub-gw
c2b.register.url.validation=${host.gat|eway}/register/validation
```

Go to definition from `${host.gat|eway}` should go to the `host.gateway`

**Comment by datho7561** [comment]
I am interested in working on this. This would likely be implemented in [lsp4mp](https://github.com/eclipse/lsp4mp), and would depend on code added in [this PR](https://github.com/eclipse/lsp4mp/pull/13)

**Comment by datho7561** [comment]
Should go to definition on `${host.gat|eway}` go to `|host.gateway=http://localhost:21301/fedahub-gw` or should it go to the same spot as go to definition on `|host.gateway=http://localhost:21301/fedahub-gw`?
