### ISSUE TITLE
Deadlock when client is sending burst of request

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/quarkus-ls#338]
In IJ Quarkus, when the IDE starts, if several Java files are opened, we will send a didOpen request for each file. The server will send back a getProjectLabels request for each file and this causes a deadlock. The reason is that each LSP request method should not run in the calling thread because it prevents the server to read the input stream of LSP4J is single thread per connection.

**Comment by angelozerr** [comment]
@jeffmaury is this issue is fixed on IJ?

**Comment by jeffmaury** [comment]
I fixed it on the IJ side but I'm still facing deadlock (mainly at IDE startup or shutdown when a bunch of files are opened or closed). Need to analyze the thread dump but I would keep it open

**Comment by jeffmaury** [comment]
See https://github.com/redhat-developer/intellij-quarkus/issues/416

**Comment by jeffmaury** [comment]
The issue is now being reported by users more frequently. Seems it should be moved to LSP4MP. Can we expect a fix and release or should I try to fix it on the IJ side (clone LSP4MP class and fix it there).

**Comment by fbricon** [comment]
mmm we could probably reproduce the problem in vscode by opening several tabs in several groups. 
I dunno when this can be fixed on the lsp4mp side though.

**Comment by angelozerr** [comment]
@fbricon can your reproduce it on vscode?

**Comment by jeffmaury** [comment]
My feeling is that it is linked on the IntelliJ internal threading model that is very constrained and deals with locks:ex you can do a search on the Java model while indexing is running

**Comment by fbricon** [comment]
@angelozerr I haven't tried TBH, I'm working on something else

**Comment by angelozerr** [comment]
The thing which is very annoying is that we never encounter the problem in vscode and I think in Eclipse IDE. More we have another language server like XML  which follows the same strategy than MP LS and we never done that.

In other words, if it's an IJ issue please fix the LSP for IJ, otherwise we should fix it in MP LS if we have the  same problem with vscode and Eclipse IDE.

**Comment by jeffmaury** [comment]
There is no way to fix it in IJ except cloning one LSP4MP class and applying the fix that should be done in LSP4MP. But if it's the only way to do it, I'll go that route.
The current LSP4MP implementation relies on the fact that the peer is able to process messages at the same rate LSP4MP which may be not true in all case

**Comment by angelozerr** [comment]
I wonder if the fix should be done on lsp4j side?

If no could you create a pr please and better with tests?

**Comment by jeffmaury** [comment]
https://github.com/eclipse/lsp4mp/pull/178
