### ISSUE TITLE
Unknown property warning for quarkus.container-image properties

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/quarkus-ls#341]
With the quarkus-container-image-jib dependency in the project's pom.xml, unknown property warnings appear for each of the quarkus.container-image properties in application.properties.

![image](https://user-images.githubusercontent.com/695993/86885167-18928f00-c0f5-11ea-8831-f383e9487600.png)

Originally reported on https://github.com/redhat-developer/intellij-quarkus/issues/177

**Comment by angelozerr** [comment]
Duplicat eof https://github.com/redhat-developer/quarkus-ls/issues/315
