### ISSUE TITLE
Documentation shows comment delimiters if Javadoc is on one line

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/quarkus-ls#35]
Compare :
<img width="709" alt="Screen Shot 2019-08-15 at 8 48 34 PM" src="https://user-images.githubusercontent.com/148698/63118441-20f25080-bf9e-11e9-9e46-f4194204c054.png">

to :
<img width="591" alt="Screen Shot 2019-08-15 at 8 50 14 PM" src="https://user-images.githubusercontent.com/148698/63118526-5139ef00-bf9e-11e9-8ad1-63333e8e8533.png">

this is a regression as you can see from https://github.com/redhat-developer/quarkus-ls/pull/28#issuecomment-520873072

**Comment by angelozerr** [comment]
Indeed i know this problem. For the moment i return just the javadoc by using jdt javadoc range if sources is available. My work is not finsished, i need to

* remove slash and star of javadoc
* concert javadoc on markdown if client support it

Please rename this issue like "improve javadoc extraction"

**Comment by fbricon** [comment]
But this worked in https://github.com/redhat-developer/quarkus-ls/pull/28#issuecomment-520873072:
![image](https://user-images.githubusercontent.com/20326645/62951741-78cf6280-bdb8-11e9-8d61-d36611e98d3f.png)

**Comment by angelozerr** [comment]
It worked because we are in case where we have not the sources. In this case docs comes from the quarkus-javadoc.properties file stored in the jar.
