### ISSUE TITLE
Was it possible to provide a NetBeans plugin?

### ISSUE THREAD

**Issue by humphreygao** [redhat-developer/quarkus-ls#359]

**Comment by fbricon** [comment]
It is technically possible for someone to provide a NetBeans plugin, provided that NetBeans supports the LSP. Our team simply doesn't have the bandwidth (nor the experience) to tackle such task, so this would be a community effort, provided there are volunteers to do it.
Right now we're still in the process of consolidating documentation on how to proceed (and with summertime, it'll take a while), but you might get an overview of the Microprofile Language Server from https://github.com/redhat-developer/vscode-quarkus/blob/master/CONTRIBUTING.md
