### ISSUE TITLE
CodeLens URL does not respect quarkus.http.root-path property

### ISSUE THREAD

**Issue by clochardpagan** [redhat-developer/quarkus-ls#368]
If we set ```quarkus.http.root-path``` to point at ```/some/special/place/in/your/heart```, and try to fire up VS Code, lens will be generated with default host ```http://localhost:8080/{some-place-specified-with-@Path-annotaion}```.

There was a pull request by @angelozerr which added support for port change - thanks, mate. @fbricon merged it on 27th of January. But... we have two more problems:

- there is no option to work with host differing from ```localhost```. That's a problem.
- there is no option to work with ```https://``` at all. Bad, but can be fixed via SSL termination or/and proxy.

**Comment by clochardpagan** [comment]
As an alternative to properties support extension, it is also possible to add support for ```@ApplicationPath``` annotation (it is a part for MicroProfile anyway). Maybe it is a better idea.

**Comment by angelozerr** [comment]
Sorry @clochardpagan I see your issue now.

I didn't know this property `uarkus.http.root-path`, we should indeed manage this case.

> there is no option to work with host differing from localhost. That's a problem.

Indeed the check which is done to show/hide CodeLens is done here https://github.com/eclipse/lsp4mp/blob/ab86a54e2be98c20ada1664ce910a015779c6b4d/microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/internal/jaxrs/java/JaxRsCodeLensParticipant.java#L99

It's very basic: check if we can connect a Socket to the localhost on a given port. The question is how to know the host (which config can we use)? 

> there is no option to work with https:// at all. Bad, but can be fixed via SSL termination or/and proxy.

Same question, how to generate URL with https (which config can we use?)

> As an alternative to properties support extension, it is also possible to add support for @ApplicationPath annotation (it is a part for MicroProfile anyway). Maybe it is a better idea.

Indeed we should manage this annotation too.

**Comment by rgrunber** [comment]
As a minor quibble, if you auto-complete the `quarkus.http.root-path`, it auto-inserts the default value, `/`. However, if you specify some value that doesn't start with `/`, you'll get the following error at runtime :

`[error]: Build step io.quarkus.vertx.http.deployment.devmode.console.DevConsoleProcessor#setupDeploymentSideHandling threw an exception: java.lang.IllegalArgumentException: Path must start with /`

Might be nice to add an easy validation if it isn't too much effort, as the error stacktrace can make it difficult to get to the exact root cause.

**Comment by angelozerr** [comment]
> * there is no option to work with host differing from localhost. That's a problem.

@clochardpagan could you give us how to you can configure the host in quarkus application please?

> * there is no option to work with https:// at all. Bad, but can be fixed via SSL termination or/and proxy.

@clochardpagan how do you enable SSL? Do you use quarkus ssl property https://quarkus.io/guides/http-reference#providing-a-certificate-and-key-file ? If it that it means that we could generate https when we find in the application.properties a quarkus ssl property.
