### ISSUE TITLE
Channel configuration used by Emitter not recognized as valid

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/quarkus-ls#369]
I have a `voting-booth` Kafka channel that is written into via an Emitter:
https://github.com/fbricon/quarkus-spread-poll/blob/9974a7a872878d53d21d36fff95f996fe647faef/src/main/java/foo/bar/poller/PollResource.java#L25-L27

However, its configuration is shown as unknown in application.properties, as there's not @Outgoing annotation for that channel:
<img width="1227" alt="Screenshot 2020-11-01 at 18 26 26" src="https://user-images.githubusercontent.com/148698/97809837-c9f29d00-1c6f-11eb-9533-93430c95b292.png">

**Comment by angelozerr** [comment]
At first I think this issue is for LSP4MP.

I don't know Emitter, if i understand correctly your issue, when Emiter annotation is used, it must generate incoming and outgoing properties?
