### ISSUE TITLE
Wrong P2 packaging for release since 0.10.0

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/quarkus-ls#389]
The release P2 repository for 0.10.0 (https://download.jboss.org/jbosstools/vscode/stable/builds/quarkus-jdt/2021-04-02_14-14-36-B4152/all/repo/) does have the date qualifier where snapshots builds or previous 0.9.0 (https://download.jboss.org/jbosstools/vscode/stable/builds/quarkus-jdt/2021-03-13_12-35-31-B4143/all/repo/) release have them.
This causes issues for consumers

**Comment by rgrunber** [comment]
Looks like the same changes we made to have lsp4mp producing OSGI bundles with proper qualifiers also needs to be made here. The reason "B4143" is fine, is because the build is based off of a development branch commit. B4152 is based off of the commit created by the Quarkus LS GitHub bot.

**Comment by rgrunber** [comment]
This should be resolved now for future builds. @fbricon actually updated the old build to add -SNAPSHOT to the version for bundles under quarkus.jdt.ext, and this will be carried forward into the new build.
