### ISSUE TITLE
Can't find 0.11.0-SNAPSHOT

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/quarkus-ls#391]
We can't find 0.11.0-SNAPSHOT on Nexus, any reason ?

**Comment by fbricon** [comment]
Have you checked your Jenkins job, it's the one pushing it to JBoss Nexus?

**Comment by jeffmaury** [comment]
No, am I really the owner of this ?

**Comment by fbricon** [comment]
I'm sure the team can take ownership at some point ;-)

**Comment by rgrunber** [comment]
https://repository.jboss.org/nexus/content/repositories/snapshots/com/redhat/microprofile/com.redhat.quarkus.ls/0.11.0-SNAPSHOT/
https://download.jboss.org/jbosstools/vscode/snapshots/builds/quarkus-jdt/latest/all/repo/

We're publishing snapshots after the migration. Marking as closed for now.
