### ISSUE TITLE
Issues found while working on the Qute LS PR

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/quarkus-ls#432]
I have a project with the following classes:

```java
package qute1;

public class Class1 {
	private String name;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
}
```

```java
package qute1;

import java.util.Collection;

public class MyData {
	private boolean available;
	
	private long longQuantity;
	
	private int intQuantity;
	
	private Collection<String> stringCollection;
	
	private String[] stringArray;

	public String[] getStringArray() {
		return stringArray;
	}

	public void setStringArray(String[] stringArray) {
		this.stringArray = stringArray;
	}

	public boolean isAvailable() {
		return available;
	}

	public void setAvailable(boolean available) {
		this.available = available;
	}

	public long getLongQuantity() {
		return longQuantity;
	}

	public void setLongQuantity(long longQuantity) {
		this.longQuantity = longQuantity;
	}

	public int getIntQuantity() {
		return intQuantity;
	}

	public void setIntQuantity(int intQuantity) {
		this.intQuantity = intQuantity;
	}

	public Collection<String> getStringCollection() {
		return stringCollection;
	}

	public void setStringCollection(Collection<String> stringCollection) {
		this.stringCollection = stringCollection;
	}
	
	public int add(int a, int b) {
		return a+b;
	}

	public boolean greater(int max) {
		return false;
	}
}
```

# ~Problem 1~

Creating a template with the following content:
`{@ data}`
Asking for code completion after the @ list the classes nut accepting one of them leads to:
`{@qute1.Class1 class1  data}`

reported as https://github.com/redhat-developer/quarkus-ls/issues/459

# ~Problem 2~

Also please note that asking for completion after the dot:
{@qute1. data}

is ineffective (no proposals)

reported as https://github.com/redhat-developer/quarkus-ls/issues/459

# ~Problem 3~

Also the following content is reported valid:

```
{@qute1.MyData data}
{data.}
```

# ~Problem 4~

Method `or(arg: java.lang.Object): java.lang.Object` is not proposed when completion is performed after the dot on `{data.}`

`{data.or('John')}` is reported as error

reported as https://github.com/redhat-developer/quarkus-ls/pull/506

# Problem 5

Code completion on { does not propose #
Code completion on {# does not propose if

reported as https://github.com/redhat-developer/quarkus-ls/issues/538

~Code completion on {#if data. does not propose members~

#  ~Problem 6~

Unparsed sections are parsed

{| <script>if(true){alert('Qute is cute!')};</script> |}

# ~Problem 7~

Non tag reported as error

`{{data1}}`

reported as https://github.com/redhat-developer/quarkus-ls/issues/443

# ~Problem 8~

```
{#with data}
{/}
```

proposes `data` when code completion after {

reported as https://github.com/redhat-developer/quarkus-ls/issues/446

# Problem 9

or operator not supported

{data or 'John'}

reported as https://github.com/redhat-developer/quarkus-ls/issues/519

# Problem 10

Completion/validation on arrays does not work

`{data.stringArray.}` is valid, no completion after the dot, any value after the dot is accepted

reported as https://github.com/redhat-developer/quarkus-ls/issues/525

# ~Problem 11~

Virtual methods accepts any parameters:

`{data.add(a1, b1)}`

reported as https://github.com/redhat-developer/quarkus-ls/issues/486

# Problem 12

Infix notation

{data greater 5} reports 5 as unknown and code completion does not propose greater

reported as https://github.com/redhat-developer/quarkus-ls/issues/519

**Comment by angelozerr** [comment]
@jeffmaury thanks so much for reporting those issues!

> Problem 7
>Non tag reported as error
> {{data1}}

It should work ?

![image](https://user-images.githubusercontent.com/1932211/143186639-310a0d47-b31e-43b4-9574-833e7109770a.png)

**Comment by angelozerr** [comment]
> Problem 3
>Also the following content is reported valid:

>{@qute1.MyData data}
>{data.}

It should be fixed now:

![image](https://user-images.githubusercontent.com/1932211/143189472-61d8f7f1-5ee9-4880-a793-696a1bf50b15.png)

**Comment by jeffmaury** [comment]
> @jeffmaury thanks so much for reporting those issues!
> 
> > Problem 7
> > Non tag reported as error
> > {{data1}}
> 
> It should work ?
> 
> ![image](https://user-images.githubusercontent.com/1932211/143186639-310a0d47-b31e-43b4-9574-833e7109770a.png)

No see the definition: https://quarkus.io/guides/qute-reference#identifiers

**Comment by angelozerr** [comment]
> Problem 6
>Unparsed sections are parsed

>{| <script>if(true){alert('Qute is cute!')};</script> |}

It should fixed (for CDAta syntax coloration, I have pushed a PR for that)

![CDataDemo](https://user-images.githubusercontent.com/1932211/143201832-3322231a-8df1-4199-b8b4-bd7c265455eb.gif)

**Comment by rgrunber** [comment]
Do all problems have a corresponding bug ? If so let's close this issue.

**Comment by angelozerr** [comment]
> Do all problems have a corresponding bug ? If so let's close this issue.

No but you are right we need to create a bugs per problem to close it. I will do that.

**Comment by angelozerr** [comment]
Ok I create all the missing issues. I close this issue.
