### ISSUE TITLE
Extract missing Quarkus properties from quarkus-cheat-sheet

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/quarkus-ls#44]
Today we compute Quarkus properties from JAR which hosts classes annotated with ConfigRoot, ConfigItem and ConfigGroup. It works but there are some limitations:

 * some properties name cannot be computed like hibernate, see https://github.com/redhat-developer/quarkus-ls/issues/29
 * some properties values cannot be extracted. Some enumeration cannot be extracted like Level (which is class an dnot enum) for log

One idea is to use https://lordofthejars.github.io/quarkus-cheat-sheet/ which declares in HTML table thoses parameters. An idea is to develop a SAX parser which collect those informations and build a JSON file with those informations.

@fbricon  what do you think about that?

**Comment by fbricon** [comment]
We now have access to deployment jars, this is no longer necessary
