### ISSUE TITLE
Validation severity settings 

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/quarkus-ls#451]
It should be nice for each validation error code to give the capability to configure the severity https://github.com/redhat-developer/quarkus-ls/blob/8645a4361425e1783b3cb5b3503f0afa1da3f879/qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/diagnostics/QuteErrorCode.java#L24 like we have for microprofile-config.properties LS

**Comment by rgrunber** [comment]
@fbricon , is it worth it to allow users to configure the diagnostics reported in https://github.com/redhat-developer/quarkus-ls/blob/master/qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java ? I would think if we set some sane defaults, this wouldn't be as necessary.

**Comment by fbricon** [comment]
For now the one diagnostic that might be worthwile is the "unresolved" error. We return a warning, qute throws an error.

**Comment by angelozerr** [comment]
It depends how teh Qute template engien is initialized. The Qute support inside Quarkus provides this settings at https://quarkus.io/guides/qute-reference#quarkus-qute_quarkus.qute.property-not-found-strategy

IMHO I think we should manage the severity according to this value coming from application.properties. But it's an another issue. 

Perhaps we could provide too `quarkus.qute.property-not-found-strategy` as Qute LS settings (when Qute is not used with Quarkus)?

**Comment by angelozerr** [comment]
After discussion with @fbricon we think this issue should be implemented before the release because we don't support the full syntaxes of Qute like:

 * https://github.com/redhat-developer/quarkus-ls/issues/525 today it reports this error

![image](https://user-images.githubusercontent.com/1932211/148772286-2cfde7c0-72d0-4b9a-9f73-e8c109643035.png)

 * https://github.com/redhat-developer/quarkus-ls/issues/519 today it reports this error (UndefinedVariable)

![image](https://user-images.githubusercontent.com/1932211/148772499-516089c8-bfbc-4fa4-8468-05b5f11f6065.png)

Those errors are really annoying because the problem is not about Qute but about our Qute support. By waiting for implementing those Qute syntaxe implementation, we need to ignore error by set a severity for UndefinedVariable (to none) with a settings like we have for application.properties https://github.com/redhat-developer/vscode-microprofile/blob/41fcae7c89116a4b28b6e0188d0ab616ce385d03/package.json#L116

We should define all https://github.com/redhat-developer/quarkus-ls/blob/master/qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/diagnostics/QuteErrorCode.java as settings to configure the severity.

For the code which get the severity,I suggest to follow the same code than https://github.com/eclipse/lsp4mp/blob/36c78ec47bf7541309b15bb548fd6e5dabafb919/microprofile.ls/org.eclipse.lsp4mp.ls/src/main/java/org/eclipse/lsp4mp/services/properties/PropertiesFileValidator.java#L114 (without property name, `we don't need pattern` in our case).

In  other words we could have 

`DiagnosticSeverity severity = validationSettings.getUndefinedVariable().getDiagnosticSeverity();`

**Comment by angelozerr** [comment]
This issue is fixed for undefined object withhttps://github.com/redhat-developer/quarkus-ls/pull/539. For other error code, we will create another issues.
