### ISSUE TITLE
#let not properly supported

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/quarkus-ls#467]
Given:
```html
<!DOCTYPE html>
<html lang="en">
<body>
{#let title="Hello World"}
  {title}
{/}
</body>
</html>
```
`title` shows an error as being unresolved and the parser complains about `let` being unterminated, but this is valid Qute content (runs fine).

![Screenshot 2021-12-01 at 19 07 27](https://user-images.githubusercontent.com/148698/144289501-f94f8b5b-dde2-4e39-9575-ceb235a3b64f.png)

**Comment by angelozerr** [comment]
Very strange it works for me. The second error comes from the real qute parser, I don't understand the error andI don't understand why you have not problem in your app.

Could you try to create a qute template `abcd.qute.html`  and copy/paste your Qute content. Is it working better?

**Comment by angelozerr** [comment]
.Oh I think you have a classpath problem. title cannot be retrieved but it seems that java.lang.String cannot be retrieved.

**Comment by fbricon** [comment]
I can't reproduce it anymore. I've seen some fishy diagnostic errors now and again, which I believe are cause by the qute AST or cache being desynchronized somehow.

I'll close this one and reopen a new issue if I see other caching problems.
