### ISSUE TITLE
Iteration metadata support not properly implemented

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/quarkus-ls#468]
According to https://quarkus.io/guides/qute-reference#loop_section: 

> It’s also possible to access the iteration metadata inside the loop via the following keys:
> - count - 1-based index
> - index - zero-based index
> - hasNext - true if the iteration has more elements
> - isLast - true if hasNext == false
> - isFirst - true if count == 1
> - odd - true if the zero-based index is odd
> - even - true if the zero-based index is even
> - indexParity - outputs odd or even based on the zero-based index value
> 
> However, the keys cannot be used directly. Instead, a prefix is used to avoid possible collisions with variables from the outer scope. By default, the alias of an iterated element suffixed with an underscore is used as a prefix. For example, the hasNext key must be prefixed with it_ inside an {#each} section: {it_hasNext}.
> 
```html
{#each items}
  {it_count}. {it.name} 
  {#if it_hasNext}<br>{/if} 
{/each}
```
Currently, completion offers the raw metadata keys (index, count...) instead of the prefixed flavor (it_count or item_count, depending on the alias), which is incorrect (the app will fail to run). 
And validation fails for the correct prefixed keys:

![Screenshot 2021-12-01 at 19 23 18](https://user-images.githubusercontent.com/148698/144291662-4befd20a-c56a-4a7b-8274-dd127ad17fcf.png)

**Comment by fbricon** [comment]
As a side effect, this causes additional errors when assigning an iteration metadata in a #let instruction (this is totally valid):
<img width="907" alt="Screenshot 2021-12-07 at 12 07 08" src="https://user-images.githubusercontent.com/148698/145018558-7403d56f-6163-4e6d-ba60-f59ac71796ac.png">

**Comment by fbricon** [comment]
Please also note the naming strategy varies, depending on:

<img width="1293" alt="Screenshot 2021-12-07 at 16 19 14" src="https://user-images.githubusercontent.com/148698/145056393-cb84deaf-f72a-4795-a9fc-96e5611ab9d2.png">

**Comment by angelozerr** [comment]
> Please also note the naming strategy varies, depending on:

I think we should have a vscode settings too to manage that (in a standalone Qute using). Perhaps we could start with this settings and in the future we could manage this settings from the application.properties too (which is harder to implement than vscode settings).
