### ISSUE TITLE
Loop parameter leak into for-else block

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/quarkus-ls#482]
When a for loop has an [else](https://quarkus.io/guides/qute-reference#loop_section) bock, the item parameter leaks into that else block, it shouldn't be accessible.
```
{#for item in items}
  {item.name}
{#else}
    {ite|}
  No items.
{/for}
```
<img width="1104" alt="Screenshot 2021-12-13 at 12 39 21" src="https://user-images.githubusercontent.com/148698/145805818-b9bdeaa6-f611-4f5d-bd5e-64fdd95c075d.png">

<img width="1073" alt="Screenshot 2021-12-13 at 12 36 46" src="https://user-images.githubusercontent.com/148698/145805575-fb4f6fde-83d6-4f03-b4f7-9c960736aec8.png">

**Comment by angelozerr** [comment]
This issue requires to improve Qute parser to consider that section (like #else) belong to a an another section (ex : #for).

Today the AST is like

```
- #for
-- #else (the AST parent of #else is the #for)
--/for
```

It should be like this:

```
- #for
- #else (the AST parent of #else is the template)
--/for
```

Even it is not the same feature, it looks like https://github.com/redhat-developer/quarkus-ls/issues/435
