### ISSUE TITLE
Ignore/include properties in application.properties depending on test scope

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/quarkus-ls#5]
According @fbricon:

We need to consider the "test" flag of the source directory the application.properties is coming from. 

 * if no "test" flag, then key/value pairs from test dependencies should not be considered to be returned to the client (edited) 

 * if "test" flag is on, then key/value pairs from test dependencies should also be returned (edited) 

As a use case, imagine an application.properties in src/test/resources, that would be able to use a specific test database (from a quarkus extension available in the test scope), in order to override a production DB defined in src/main/resources/application.properties

**Comment by emmanuelbernard** [comment]
For info we have `%test.` prefix in the `src/main/resource/application.properties` file. I don't think we ever advertised the used of `src/test/resource/application.properties`.
It seems to work by accident.
