### ISSUE TITLE
Extension methods should be filtered and applied only on compatible types

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/quarkus-ls#507]
If we have an Item object, we shouldn't see completion of extensions for List, Map and other unrelated objects.

<img width="1066" alt="Screenshot 2022-01-03 at 11 58 47" src="https://user-images.githubusercontent.com/148698/147923437-8ebedae7-e7ee-4dfc-9bbb-b5ac2f0cb52d.png">

The 1st parameter of the extension method should match the type of the parameter being completed. Same thing should be applied for validation.

**Comment by angelozerr** [comment]
I cannot reproduce it, could you share please your Qute template?

**Comment by fbricon** [comment]
sorry I was actually using an old build. Looks good now.
