### ISSUE TITLE
Varargs are not properly supported in Qute template validation

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/quarkus-ls#509]
Given a template extension method with varargs, such as : 
```java
@TemplateExtension
public class TemplateExtensions {

    static String pretty(Item item, String... elements) { 
        return item.name + " "+ String.join(", ", elements);
    }
}
```
Validation fails in the Qute template for: 

```
{item.pretty("one", "two")}
```
> The method `pretty(String[])` in the type `TemplateExtensions` is not applicable for the arguments `(String, String)`. qute(InvalidMethodParameter)

<img width="937" alt="Screenshot 2022-01-04 at 17 51 57" src="https://user-images.githubusercontent.com/148698/148095550-7cf8eda2-2aec-4f98-b603-1a84f4c5cd92.png">

**Comment by rgrunber** [comment]
Just for information, `public boolean org.eclipse.jdt.core.dom.IMethodBinding#isVarargs()` could be used to determine this. If you can get the `MethodInvocation`, which is an `ASTNode`, it has `resolveMethodBinding()` which should return the `IMethodBinding`
