### ISSUE TITLE
Support for Infix notation

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/quarkus-ls#519]
The PR https://github.com/redhat-developer/quarkus-ls/pull/506 will support or resolver with the following syntax : 

`{name.or('John')}`

The support provides: 

 * completion after` name. `(it will show `or` method)
 * validation for `or` method
 * hover for `or` method (documentation about `or` method)

Qute supports too the another syntax:
 
`{name or 'John'}`

Today we don't support it and validation says that `or` is udenfined:

![image](https://user-images.githubusercontent.com/1932211/148413136-0f7b94ef-6167-4474-97a8-cb3bd7f18bb3.png)

It seems Qute have a generic mechanism and this syntax can be used too for another methods (ex : for get of List), you can write

```
{items.get(0)}
{items get 0}
```

Supporting the syntax {`items get 0`} is not trivial, I wonder if Qute will continue to provide this syntax when it will adopt new parser (with ANTLR, if I understood correctly). 

If this syntax will be supported, we need to suppor it too. The strange thing is that it works only with method which have parameters. Ex if you write 

`{items orEmpty}` this syntax fails.

@mkouba @maxandersen  do you think this syntax will be continued to support it in the future?

**Comment by mkouba** [comment]
> Qute supports too the another syntax:

You can also use the elvis operator: `{name ?: 'John'}` which is also an equivalent of `.or('John')`.

> Supporting the syntax {items get 0} is not trivial, I wonder if Qute will continue to provide this syntax when it will adopt new parser (with ANTLR, if I understood correctly).

We call it "infix notation" and it's even mentioned in the docs. I don't see why a new parser (if we ever have one) should not support this.

> The strange thing is that it works only with method which have parameters. Ex if you write...

The [documentation](https://quarkus.io/guides/qute-reference#virtual_methods) is clear that _"it can be used for virtual methods with **single parameter**"_.

**Comment by angelozerr** [comment]
Thanks @mkouba for you clarification! We must definitely support thoses syntaxes.

**Comment by mkouba** [comment]
> I wonder if ANTLR can manage that easily?

I have no idea :thinking:

**Comment by angelozerr** [comment]
@mkouba I'm working on my Qute parser to support infix notation and I noticed that number of space is very important:

 * `{name or 'John'}` is working
 * `{name  or 'John'}` fails (there are 2 spaces after name). Is it an expected behavior?

**Comment by mkouba** [comment]
>  Is it an expected behavior?

Hm, I would not say it's expected but a single space was intended for use ;-). We could try to be a more lenient but I don't think it's reasonable to support something like {name&nbsp;&nbsp;&nbsp;&nbsp;or&nbsp; &nbsp;`John`}.

**Comment by angelozerr** [comment]
The main problem with several spaces is that it's difficult for the user to understand the error:

```
Caused by: io.quarkus.qute.TemplateException: Method "(or)" not found on the base object "java.lang.String" in expression {name.(or).'John')} in template 1 on line 3
	at io.quarkus.qute.EvaluatorImpl.propertyNotFound(EvaluatorImpl.java:207)
	at io.quarkus.qute.EvaluatorImpl.resolve(EvaluatorImpl.java:169)
```

There are 2 options:

 * you want to keep the rule of one space: the validation should say that there are too many spaces. I could manage that in our Qute validator and provide a quickfix which remove extra spaces.
 * you can manage several spaces in the future Qute parser, I will not work on the quickfix which removes extra spaces.

**Comment by mkouba** [comment]
I'll try to add support for multiple spaces for infix notation and ping you ;-).

**Comment by angelozerr** [comment]
> I'll try to add support for multiple spaces for infix notation and ping you back ;-).

Thanks so much! My Qute current work with parser is working like this for the moment.

**Comment by mkouba** [comment]
FYI https://github.com/quarkusio/quarkus/pull/22900

**Comment by maxandersen** [comment]
Thanks @mkouba the "space count matters" caught me of guard multiple times. nice to see it improved!
