### ISSUE TITLE
Add proper array support in Qute templates

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/quarkus-ls#525]
See https://quarkus.io/guides/qute-reference#arrays

> You can iterate over elements of an array with the Loop Section. Moreover, it’s also possible to get the length of the specified array and access the elements directly via an index value. Additionaly, you can access the first/last n elements via the take(n)/takeLast(n) methods.

Example
```
<h1>Array of length: {myArray.length}</h1> 
<ul>
  <li>First: {myArray.0}</li> 
  <li>Second: {myArray[1]}</li> 
  <li>Third: {myArray.get(2)}</li> 
</ul>
<ol>
 {#for element in myArray}
 <li>{element}</li>
 {/for}
</ol>
First two elements: {#each myArray.take(2)}{it}{/each} 
```

**Comment by angelozerr** [comment]
The arrays support should work for the all cases except with bracket:

`<li>Second: {myArray[1]}</li> `

I need to update the parser to take care of this usecase.

**Comment by angelozerr** [comment]
fixed with https://github.com/redhat-developer/quarkus-ls/pull/607
