### ISSUE TITLE
Add location link support for `@Location` annotation value.

### ISSUE THREAD

**Issue by AlexXuChen** [redhat-developer/quarkus-ls#526]
Consider the following Quarkus project snippet:
```java
@Location("detail/items2_v1.html")
@Inject
Template hallo;
```

Currently there is support for the attribute variable definition location link. It would be nice to also have a location link for the Qute template location assigned to the `@Location` annotation.

**Comment by angelozerr** [comment]
Fixed by https://github.com/redhat-developer/quarkus-ls/pull/653
