### ISSUE TITLE
CodeAction to disable validation

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/quarkus-ls#531]
When there is an error in qute template it should be nice to provide a code action to disable validation in other words update the proper validation settings like we do for application.properties validation.

When validation settings severity for each error code will be implemented it should be nice to provide an another code action to disable the settings for the given error code.

**Comment by angelozerr** [comment]
I reopen the issue because we need to manage code action to disable validation but for a given file.

@fbricon have you some idea about the settings name that we can use it to define a set of templates. 

A quick idea  `quarkus.tools.qute.validation.excluded` String array:

```json
"quarkus.tools.qute.validation.excluded" : [
  "*.items.qute.html"
  "*.book.qute.*"
]
```

It's simple but not powerfull (ex : we cannot configure some severity fo some error code for a given set of files). 

@fbricon what do you think?

**Comment by fbricon** [comment]
It's good enough.

**Comment by angelozerr** [comment]
> It's good enough.

Ok thanks. I will implement it. The idea is to have 2 code actions:

 * `Disable Qute validation` updates `quarkus.tools.qute.validation.enabled` to false (disable validation for all templates). We have that in master.
 * `Disable Qute validation for this file` will add the file in the "quarkus.tools.qute.validation.excluded"  String array.

I wonder if we need a code action like `Disable Qute validation for '*/items.qute.*` pattern` ?

**Comment by fbricon** [comment]
keep it simple for now, just this file pattern.

**Comment by angelozerr** [comment]
Fixed by https://github.com/redhat-developer/quarkus-ls/pull/535
