### ISSUE TITLE
Add support for `raw` and `safe` extension methods, to escape characters

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/quarkus-ls#533]
See https://quarkus.io/guides/qute-reference#character-escapes

> For HTML and XML templates the `'`, `"`, `<`, `>`, `&` characters are escaped by default if a template variant is set.
>
> In Quarkus, a variant is set automatically for templates located in the `src/main/resources/templates`. By default, the `java.net.URLConnection#getFileNameMap()` is used to determine the content type of a template file. The additional map of suffixes to content types can be set via `quarkus.qute.content-types`.
If you need to render the unescaped value:
>
>Either use the `raw` or `safe` properties implemented as extension methods of the `java.lang.Object`,
>
>Or wrap the String value in a `io.quarkus.qute.RawString`.
>
```html
<html>
<h1>{title}</h1> 
{paragraph.raw} 
</html>
```
>title that resolves to `Expressions & Escapes` will be rendered as `Expressions &amp; Escapes`
paragraph that resolves to `<p>My text!</p>` will be rendered as `<p>My text!</p>`

**Comment by fbricon** [comment]
`raw` and `safe` currently cannot be resolved thus generate validation errors:
![Screenshot 2022-01-12 at 12 25 48](https://user-images.githubusercontent.com/148698/149131739-6471eee9-e2ce-4429-8a4d-a06ef351f600.png)

**Comment by angelozerr** [comment]
This issue should b eeasy to do, but please wait for the merge of https://github.com/redhat-developer/quarkus-ls/pull/530 before working on it.

**Comment by AlexXuChen** [comment]
@mkouba Do `raw` and `safe` have the same or different behaviour?

**Comment by mkouba** [comment]
> @mkouba Do `raw` and `safe` have the same or different behaviour?

The same, see also https://quarkus.io/guides/qute-reference#character-escapes.

**Comment by angelozerr** [comment]
@mkouba could you review please description of raw and safe value resolver in 

 * https://github.com/redhat-developer/quarkus-ls/pull/543/files#diff-c28fff7d72fe57edc7df92a5ff5442896074ca8b69a74973211ceebee96f416bR95
 * https://github.com/redhat-developer/quarkus-ls/pull/543/files#diff-c28fff7d72fe57edc7df92a5ff5442896074ca8b69a74973211ceebee96f416bR103

**Comment by mkouba** [comment]
The description is wrong - safe/raw means "no need to escape", i.e. the string is safe to render as is...

**Comment by AlexXuChen** [comment]
@mkouba Are thess descriptions better?
- https://github.com/redhat-developer/quarkus-ls/pull/543/files#diff-c28fff7d72fe57edc7df92a5ff5442896074ca8b69a74973211ceebee96f416bR95
- https://github.com/redhat-developer/quarkus-ls/pull/543/files#diff-c28fff7d72fe57edc7df92a5ff5442896074ca8b69a74973211ceebee96f416bR103
