### ISSUE TITLE
Don't show undefined variable errors depending on context

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/quarkus-ls#548]
If a template checks a variable exists in a given context, eg. an if or for block, validation should know the variable exists and therefore should not complain about  undefined variables.eg.

<img width="826" alt="Screenshot 2022-02-03 at 10 11 37" src="https://user-images.githubusercontent.com/148698/152313825-4aa23245-c883-4e11-8afa-a7c0a7b2dcee.png">

**Comment by angelozerr** [comment]
To check if an object part is optional you can use [ObjectPart#isOptional()](https://github.com/redhat-developer/quarkus-ls/blob/b3d103104e07809dd866b9dde463cab925023cc8/qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/expression/Part.java#L121);

It's the first step to remove the error from `name??` in #if

For the second error, {name}, the main idea is to store in a list all optional part in https://github.com/redhat-developer/quarkus-ls/blob/b3d103104e07809dd866b9dde463cab925023cc8/qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java#L87

You will need to ad SectionKinf.IF in https://github.com/redhat-developer/quarkus-ls/blob/b3d103104e07809dd866b9dde463cab925023cc8/qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java#L347 to create an instance of ResolutionContext.
