### ISSUE TITLE
QuteIndexer scan may throw NPE if template folder does not exist

### ISSUE THREAD

**Issue by rgrunber** [redhat-developer/quarkus-ls#554]
Refer to https://github.com/redhat-developer/vscode-quarkus/pull/455#issuecomment-1035484366

[`project.getTemplateBaseDir()`](https://github.com/redhat-developer/quarkus-ls/blob/master/qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/indexing/QuteIndexer.java#L84) needs to be guarded because [`TEMPLATES_BASE_DIR`](https://github.com/redhat-developer/quarkus-ls/blob/master/qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/utils/JDTQuteProjectUtils.java#L42) may not exist.

**Comment by angelozerr** [comment]
@rgrunber it should be fixed in https://github.com/redhat-developer/quarkus-ls/pull/559

Could you check that please and close the issue if it's OK. Thanks.

**Comment by rgrunber** [comment]
> 

Yes, it is fixed with that PR. Closing.
