### ISSUE TITLE
Support for `textDocument/InlayHint`

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/quarkus-ls#595]
Display the Java type of parameter name as inlay hint.

See inlay hints rendererd with gray background:

![image](https://user-images.githubusercontent.com/1932211/158047287-0e5a05d7-8bb6-4bb9-9791-cf9c66f71692.png)

**Comment by angelozerr** [comment]
@FroMage @mkouba @maxandersen do you like this feature? Any ferdback ideas are welcome

**Comment by maxandersen** [comment]
If that can be done reliably and without slowing down editing I'm all for it. very nice!

**Comment by maxandersen** [comment]
I assume if type can't be inferred it just don't put any hint?

**Comment by angelozerr** [comment]
>that can be done reliably and without slowing down editing I'm all for it. very nice!

No problem with that. InlayHint belongs to lsp specification. It works like codelens. If the compute of inlay hint takes time the will not be displayed but no problem with slow down

> I assume if type can't be inferred it just don't put any hint?

Yes

I will record a demo to show more the inlay hint in action

**Comment by angelozerr** [comment]
@maxandersen here a little demo:

![InlayHintDemo](https://user-images.githubusercontent.com/1932211/158067673-dac2b99f-1651-4773-842e-0ee4b05d4d80.gif)

**Comment by maxandersen** [comment]
Looks very nice. Awesome!

**Comment by angelozerr** [comment]
Glad it pleases you!

**Comment by mkouba** [comment]
> > 
> 
> No problem with that. InlayHint belongs to lsp specification. It works like codelens. If the compute of inlay hint takes time the will not be displayed but no problem with slow down

So if the type info is not available it will just show nothing and cancel the computation in the background?

**Comment by angelozerr** [comment]
> So if the type info is not available it will just show nothing and cancel the computation in the background?

Yes, you can see this behavior inthe demo when there is `item in items` where items doesn't exists, so item java type ca,,ot be computed. In this case it displays nothing.

**Comment by FroMage** [comment]
I like displaying the type on declaration, that makes sense (think `var` in Java, IDEs do the same). But on usage, when you pass it as parameter, I find it weird, no? Do IDEs do that, normally? I don't think they do.

**Comment by angelozerr** [comment]
> I like displaying the type on declaration, that makes sense (think var in Java, IDEs do the same). But on usage, when you pass it as parameter, I find it weird, no? Do IDEs do that, normally? I don't think they do.

At first there is a settings to show type for method parameter.

Eclipse IDE provides this feature for parameter name (not type):

![image](https://user-images.githubusercontent.com/1932211/158152170-f47aa901-0644-4f03-8e3d-1b0f6deecfe3.png)

**Comment by angelozerr** [comment]
> I like displaying the type on declaration, that makes sense (think var in Java, IDEs do the same). But on usage, when you pass it as parameter, I find it weird, no? Do IDEs do that, normally? I don't think they do.

@fbricon @maxandersen @mkouba do you think we should remove display of type  for method parameter? Perhaps you would prefer displaying parameter name or nothing?

**Comment by mkouba** [comment]
>  Perhaps you would prefer displaying parameter name or nothing?

I'm not sure but I think that displaying the parameter name would be a bit more practical as the param type is validated anyway, or? AFAIK ides show the param names on the left side too.

**Comment by angelozerr** [comment]
> I'm not sure but I think that displaying the parameter name would be a bit more practical as the param type is validated anyway, or? AFAIK ides show the param names on the left side too.

Thanks for your feedback @mkouba !
