### ISSUE TITLE
Use  `quarkus.package.type=native property` to know that the project is in native mode.

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/quarkus-ls#632]
Today to work on native mode we have the `qute.native.enabled : true` settings. 

But quarkus apps usually have a pregenerated maven profile that add the `quarkus.package.type=native property`. In this case we should  switch the project to native mode.

**Comment by angelozerr** [comment]
After discussion with @mkouba it is not possible to detect that a Quarkus app is in native mode only. I close the issue but of someone have some ideas how to detect that Quarkus app is in native mode only, doesn't hesitate to give your ideas.

**Comment by jeffmaury** [comment]
My idea was not to detect native mode only but to say if we detect native settings in the Quarkus project so it's likely user will generate a native binary so `qute.native.enabled` should have a default value of `true`

**Comment by mkouba** [comment]
> but to say if we detect native settings in the Quarkus project so it's likely user will generate a native binary

The problem is that our code generators (e.g. `code.quarkus.io`) do add the native config (e.g. a maven profile) by default and I doubt that users will remove the config even if they don't target the native mode.
