### ISSUE TITLE
When Template is constructor-injected, @Location is ignored

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/quarkus-ls#637]
Following code is valid quarkus/qute, but quarkus-ls validation doesn't find page (`No template matching the path page could be found for: com.redhat.demo.SomePage`) on :

```
@Path("/some-page")
public class SomePage {

    private final Template page; // page underlined as error

    public SomePage(@Location("foo/bar/page.qute.html") Template page) {
        this.page = requireNonNull(page, "page is required");
    }

    @GET
    @Produces(MediaType.TEXT_HTML)
    public TemplateInstance get(@QueryParam("name") String name) {
        return page.data("name", name);
    }

}
```

**Comment by rgrunber** [comment]
I'm not sure if this will be possible in the most general case. Sure we could catch something like `this.page = page` and maybe even some well known library methods like `requireNonNull`, but I can easily produce some custom method whose return type can only be known at runtime, and we need to generate diagnostics using only static analysis.
