### ISSUE TITLE
Can not navigate from {inject:vertxRequest.absoluteURI} to Java code

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/quarkus-ls#642]
In a Quarkus project's template, containing {inject:vertxRequest.absoluteURI} , Ctrl+clicking on vertxRequest or absoluteURI does nothing

**Comment by angelozerr** [comment]
It sould work. Have you the sources where vertexRequest is defined? Could you open the vertexRequest with your Java editor?

**Comment by fbricon** [comment]
Can't reproduce. Closing.
