### ISSUE TITLE
Collect values for Level

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/quarkus-ls#65]
`quarkus.log.level` is bound to the Level class http://developer.classpath.org/doc/java/util/logging/Level-source.html It should be ggod to generated enums by looping for static fields of Level to retrieve ALL, SEVERE, etc enums.

**Comment by fbricon** [comment]
I'm not sure there's an easy way to generalize the solution, apart from hard coding use cases for specific classes, Level in this case

**Comment by angelozerr** [comment]
This issue is covered by https://github.com/redhat-developer/quarkus-ls/issues/69
