### ISSUE TITLE
Need to escape asterisks in Completion item documentation titles

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/quarkus-ls#66]
With the keycloak extension, complete on `quarkus.keycloak.policy-enforcer.claim-information-point` and you'll see the documentation title is rendered in a strange way. First 2 `*`'s are considered bold delimiters, they should be escaped:

<img width="746" alt="Screen Shot 2019-08-30 at 4 59 31 PM" src="https://user-images.githubusercontent.com/148698/64030991-e9f86f00-cb47-11e9-9b7e-cf3186a36c0b.png">

**Comment by fbricon** [comment]
probably the same for hover

**Comment by angelozerr** [comment]
@fbricon  @xorye let me fix this issue because I have a code which replace {*} in completion. PR will come soon.
