### ISSUE TITLE
Base "generate missing member" CodeActions on if the type is a source or binary file

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/quarkus-ls#676]
The "add field" and "add getter" code actions for missing members in Qute templates should not appear if the Java type is a binary, since the source for the class can't be modified.

The "add to existing template extensions" and "add to new template extensions" code actions for missing members in Qute templates should not appear if the Java type is a source file, since it makes more sense to add it as a field or getter to the source file.

If we know if the type is a source file or a binary file before we generate the text edits associated with the code action, we can generate only the code actions that are needed.

See https://github.com/redhat-developer/quarkus-ls/pull/671#issuecomment-1197058836

**Comment by angelozerr** [comment]
To support that I suggest that you add in https://github.com/redhat-developer/quarkus-ls/blob/8a52980f2a999e80a0367f301f8962dfaf4f84b7/qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/ResolvedJavaTypeInfo.java

```java
private Boolean source;

...

public boolean isSource() {
    return source != null && source.booleanValue();
}

```
like isTerable:

https://github.com/redhat-developer/quarkus-ls/blob/8a52980f2a999e80a0367f301f8962dfaf4f84b7/qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/ResolvedJavaTypeInfo.java#L44
