### ISSUE TITLE
AbstractQuteTemplateLinkCollector wongly identifies Template fields

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/quarkus-ls#683]
https://github.com/redhat-developer/quarkus-ls/blob/8a52980f2a999e80a0367f301f8962dfaf4f84b7/qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/java/AbstractQuteTemplateLinkCollector.java#L259

Only the last part of the field class name is used, there is a constant in QuteConstants for the whole class name

**Comment by rgrunber** [comment]
Yup! This looks like a bug. We need to check that the type matches `io.quarkus.qute.Template`, not just `Template`.

Would be good to confirm that if one defines their own type, `com.example.Template`, and annotations it with `@Location`, that it leads to bad behaviour.
