### ISSUE TITLE
QuteJavaCodeLensCollector has a private unused method

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/quarkus-ls#684]
https://github.com/redhat-developer/quarkus-ls/blob/8a52980f2a999e80a0367f301f8962dfaf4f84b7/qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/java/QuteJavaCodeLensCollector.java#L96

**Comment by rgrunber** [comment]
This method doesn't appear to have ever done anything. It was removed in https://github.com/redhat-developer/quarkus-ls/commit/bb2d2c9c7bcac2124ffb82438652e6e3df458e32#diff-1d7cfc4737077af167c0f687b94de383a2135b3987cc923f0da2ce9ff67019a6L90 . @angelozerr , is there something we're missing here ?

**Comment by angelozerr** [comment]
@rgrunber this method alread exists https://github.com/redhat-developer/quarkus-ls/blob/8bd86c7d1bb1aef8948803ee24754e3eb1dd7006/qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/java/QuteJavaCodeLensCollector.java#L96 and we should remove it.

**Comment by datho7561** [comment]
Fixed in https://github.com/redhat-developer/quarkus-ls/pull/769
