### ISSUE TITLE
Build Quarkus LS and JDT Extension for vscode-quarkus

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/quarkus-ls#7]
Manage a build 

 * for Quarkus LS : like lsp4xml (see npm run build-server) to create the Quarkus LS server and set it in the server folder of vscode-quarkus
 * for Quarkus JDT LS Extension, build the project and copy the JAR into the jars folder of vscode-quarkus

Like vscode-xml README, explain how to do that

**Comment by xorye** [comment]
Fixed thanks to [vscode-quarkus/pull/15](https://github.com/redhat-developer/vscode-quarkus/pull/15).

**Comment by fbricon** [comment]
Only thing needed is documentation now

**Comment by angelozerr** [comment]
> Only thing needed is documentation now

@xorye have you done that? Can we close this issue?

**Comment by xorye** [comment]
@angelozerr , if documentation means explanation, then yes. The explanation is in CONTRIBUTING.md.

**Comment by angelozerr** [comment]
Ok thanks @xorye
