### ISSUE TITLE
Qute generate missing member cannot generate new template extension when `TemplateExtensions` and `TemplateExtensions0` exist

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/quarkus-ls#712]
Say you have a Qute template that references a property that doesn't exist:

```html
{myObj.asdf}
```

... and you have two classes in the default package named `TemplateExtensions` and `TemplateExtensions0`.

If you apply the code action to generate a new template extensions class, then nothing happens.

**Comment by jeffmaury** [comment]
I would that the result is not nothing happens but you end up with a thread looping forever :)
