### ISSUE TITLE
Automatic tag closing can occur within template parameter declaration

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/quarkus-ls#741]
Given the following Qute template:

```qute
{@java.lang.List<java.lang.String| myStrings}
```

If you type in the missing `>` at the `|`, then the HTML automatic tag closing will activate, resulting in:

```java
{@java.lang.List<java.lang.String></java.lang.String> myStrings}
```

It would be nice if we are able to disable this feature when the cursor is within the `{@...}`.

**Comment by angelozerr** [comment]
I fear it is not possible because it is the completion result of the html langage serveur.

**Comment by datho7561** [comment]
Now that I think of it, I should have filed this under vscode-quarkus. I'm going to close this issue and recreate it there.

We could do some hacks in vscode-quarkus to improve this without any changes to VS Code, such as forcing the auto tag closing feature off while editing files labelled qute-html.

I'll look into how you have implemented reusing the HTML language server and see if I can come up with something.
