### ISSUE TITLE
Qute: First inlay hints request always fails

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/quarkus-ls#749]
When I open a qute file in a quarkus project when I first start up VS Code, the first inlay hints request from VS Code to the language server always fails, causing a popup to appear.

**Comment by angelozerr** [comment]
I think it is because langage server cancel the inlayhint.

But i think with lzst vscode langage client which supports inlay hint it should fix it.

I need to check what Im saying with the crurent code to see if it there is a cancel exception and in this case ignore it.

**Comment by rgrunber** [comment]
Any relation to https://github.com/eclipse/lsp4mp/pull/284#issuecomment-1228756441 ?

**Comment by datho7561** [comment]
This is a duplicate of redhat-developer/vscode-quarkus#503
