### ISSUE TITLE
quarkus-ls crash if quarkus/projectInfo not implemented

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/quarkus-ls#75]
I started implemented quarkus-ls in IntelliJ. As the client is the standard one, the request quarkus/projectInfo is not implemented.
I noticed that the LSP implementation reports that the quarkus-ls crashed because errors are sent back when this message is received

**Comment by jeffmaury** [comment]
Error reported:

![image](https://user-images.githubusercontent.com/695993/64414100-130e8780-d093-11e9-9fb7-315d2fc85252.png)

**Comment by angelozerr** [comment]
A clean solution is to have capability send by the client which says that `quarkus/projectInfo`  is supported by the client. But without `quarkus/projectInfo`, the Quarkus LS is not interesting (you have none Quarkus completion, hover, validation, etc)/

@fbricon do you think we should implement client capability for that?

@jeffmaury please note that Quarkus LS provides the Quarkus LS client interface 
https://github.com/redhat-developer/quarkus-ls/blob/master/quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/ls/api/QuarkusLanguageClientAPI.java that you should implement on IJ client side like I have done with my integration of Quarkus LS inside Eclipse https://github.com/angelozerr/quarkus-lsp4e/blob/master/com.redhat.quarkus.lsp4e/src/com/redhat/quarkus/lsp4e/QuarkusLanguageClient.java#L21

**Comment by angelozerr** [comment]
I think we can close this issue. I don't know how to manage that on Quarkus LS side and as this quarkus/projectInfo method is the core of Quarkus LS, I think it's very good to have a big error.

I close this issue but if you think it's important to manage it, please reopen it.
