### ISSUE TITLE
Telemetry for qute-ls

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/quarkus-ls#765]
It would be nice to know how many people are using qute-ls. In order to figure this out, we should add telemetry.

To start out, I think it would be a good idea to send an event when the user opens a Qute template. Since we just want to know if  the user is using qute-ls, I think we should only send this event for the first Qute template that they open (per run of the language server). I think this should give a rough estimate for how many people are using qute-ls.

**Comment by rgrunber** [comment]
Should this event be further expanded to include things like whether the project makes use of qute bundle on the classpath ?

**Comment by rgrunber** [comment]
Ugh you're right. qute file document open is on the Qute LS, and project import is in the Quarkus/Qute JDT extensions. It would be tricky to ensure we send the event only once in both cases :neutral_face:
