### ISSUE TITLE
QuteSupportForTemplateGenerateMissingJavaMemberHandler endless loop

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/quarkus-ls#772]
https://github.com/redhat-developer/quarkus-ls/blob/906a34fa7cb85c8da5436019f087ab05d7a08cf0/qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/QuteSupportForTemplateGenerateMissingJavaMemberHandler.java#L411

**Comment by datho7561** [comment]
Good catch! That's probably the root cause of https://github.com/redhat-developer/quarkus-ls/issues/712.

**Comment by datho7561** [comment]
See https://github.com/redhat-developer/quarkus-ls/issues/712
