### ISSUE TITLE
Initialize support for Qute `Type-safe Message Bundles`

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/quarkus-ls#800]
See https://quarkus.io/guides/qute-reference#type-safe-message-bundles

**Comment by angelozerr** [comment]
@mkouba do you know if there is a sample project with Qute which uses the https://quarkus.io/guides/qute-reference#type-safe-message-bundles ?

**Comment by mkouba** [comment]
> @mkouba do you know if there is a sample project with Qute which uses the https://quarkus.io/guides/qute-reference#type-safe-message-bundles ?

I'm not aware of such a project... :-(
