### ISSUE TITLE
CodeLens for #insert section

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/quarkus-ls#814]
It is hard to know where {#insert title} is used by another  template which include it. It should be nice to provide codelens which show references and click on codelens should find references.

![image](https://user-images.githubusercontent.com/1932211/225097300-61413c29-c95a-418f-b608-b8e2638c2f6e.png)

//cc @FroMage

**Comment by FroMage** [comment]
+1

**Comment by angelozerr** [comment]
I have started to implement this feature but I need https://github.com/redhat-developer/quarkus-ls/pull/810 //cc @datho7561

**Comment by angelozerr** [comment]
Thanks @datho7561 @JessicaJHee for your review.
