### ISSUE TITLE
Support for Evaluation of CompletionStage and Uni Objects

### ISSUE THREAD

**Issue by gastaldi** [redhat-developer/quarkus-ls#826]
### Describe the bug

When adding a CompletableFuture data item to a qute template,  eclipse shows an error:

For example: I am adding a CompletableFuture here:
<img width="592" alt="Screenshot 2023-03-24 at 09 16 25" src="https://user-images.githubusercontent.com/46684275/227476820-789b235b-b30e-4ef2-b7a0-94e0074906fb.png">

In eclipse Qute editor, I see this error :

<img width="909" alt="Screenshot 2023-03-24 at 09 18 07" src="https://user-images.githubusercontent.com/46684275/227477163-88214782-d1fc-4183-906e-e25de4636a8e.png">

If I complete the future in the java code:
<img width="557" alt="Screenshot 2023-03-24 at 09 18 59" src="https://user-images.githubusercontent.com/46684275/227477372-cf3e345d-50a0-4aeb-9bab-cda97d13bcc1.png">

The warning goes away, though the code is no longer reactive....
<img width="432" alt="Screenshot 2023-03-24 at 09 19 50" src="https://user-images.githubusercontent.com/46684275/227477597-f86b43d8-943c-4d67-a164-1fabcec742df.png">

### Expected behavior

Use of completablefuture should work the same as just passing data objects.

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18 OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8) OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

eclipse

### Additional information

Doesn't actually prevent anything from working as it should.  Just an annoying eclipse error.

Using eclipse plugin "Quarkus Tools 4.26.0.Final'

Reported by @TonyWeston in https://github.com/quarkusio/quarkus/issues/32103

**Comment by jeffmaury** [comment]
Add @angelozerr

**Comment by fbricon** [comment]
@TonyWeston can you provide a small sample project reproducing this issue please?

**Comment by angelozerr** [comment]
We need to support https://quarkus.io/guides/qute-reference#evaluation-of-completionstage-and-uni-objects

**Comment by angelozerr** [comment]
@mkouba in the sample https://quarkus.io/guides/qute-reference#evaluation-of-completionstage-and-uni-objects you speak about object part which can be a CompletionStage, but is it possible to use property or method part with CompletionStage?

**Comment by mkouba** [comment]
> @mkouba in the sample https://quarkus.io/guides/qute-reference#evaluation-of-completionstage-and-uni-objects you speak about object part which can be a CompletionStage, but is it possible to use property or method part with CompletionStage?

Yes. This sentence is crucial: "If a part of an expression resolves to a CompletionStage, the resolution continues once this stage is completed and the next part of the expression (if any) is evaluated against the result of the completed stage."

**Comment by angelozerr** [comment]
> Yes. This sentence is crucial: "If a part of an expression resolves to a CompletionStage, the resolution continues once this stage is completed and the next part of the expression (if any) is evaluated against the result of the completed stage."

Ooops sorry I have not seen that. Thanks for your answer, I cover this usecase too.
