### ISSUE TITLE
`{if !inject:beanName}{/if}` is marked as invalid

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/quarkus-ls#828]
Open https://github.com/FroMage/quarkus-renarde-todo/blob/7784cba6de7f31e937726eec6725df3c95eca1f6/src/main/resources/templates/main.html#L31 in vscode-quarkus, and it will be marked with the warning "No namespace resolver found for: `!inject`". However, this code runs fine. It would be nice if we didn't mark it as invalid.

**Comment by fbricon** [comment]
is it a regression? inject: has been supported for a while

**Comment by datho7561** [comment]
This doesn't appear to be a regression, I double checked against 1.13.0 from the marketplace

**Comment by angelozerr** [comment]
This issue should be fixed with https://github.com/redhat-developer/quarkus-ls/pull/835
