### ISSUE TITLE
Quick fix to insert all missing attributes for user tag in Qute file adds a `nested-content` attribute

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/quarkus-ls#841]
Let's say you have a user tag: (this is one from quarkus-renarde-todo)

`formElement.html`:
```qute-html
<label class="form-label" for="{name}">{label}</label>
<div class="mb-3 {class??}">
    {nested-content}
{#ifError name}
    <span class="invalid-feedback">​{#error name/}</span>​
{/ifError}
</div>
```

and you reference it from another Qute template like this:

```qute-html
{#formElement}
  <h3>Hello!</h3>
{/}
```

Then there is a quick fix that appears on `#formElement` to add all the missing attributes to the user tag. However, this quick fix adds an attribute called `nested-content`. However, `nested-content` [is a special key that gets replace with the content of the user tag](https://quarkus.io/guides/qute-reference#user_tags) (in this case `<h3>Hello!</h3>`). It doesn't makes sense to add it as an attribute with the quick fix.

**Comment by angelozerr** [comment]
@JessicaJHee coudl you look at this issue when you will have time, I think the fix should be easy.
