### ISSUE TITLE
textDocument/inlayHint fails when classpath is incorrect

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/quarkus-ls#858]
- create a Quarkus Maven project
- add an invalid dependency, eg:
```xml
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>missing</artifactId>
      <version>9.9.9</version>
    </dependency>
```
- create a user tag as src/main/resources/templates/tags/mytag.html, containing simply `{nested-content}`
- create a qute template as src/main/resources/templates/index.html, containing 
```
{#mytag}
foo
{/}
```

The Qute LS throws an exception that pops up in the user's face:

<img width="454" alt="Screenshot 2023-04-05 at 12 47 36" src="https://user-images.githubusercontent.com/148698/230060208-78d1c089-7109-4821-813f-b977d546f96c.png">

Cause:

> Received response 'textDocument/inlayHint - (91)' in 10ms. Request failed: Request qute/template/userTags failed with message: /Users/fbricon/.m2/repository/io/quarkus/missing/9.9.9/missing-9.9.9.jar does not exist (-32603).
[Error - 12:51:47] Request textDocument/inlayHint failed.
  Message: Request qute/template/userTags failed with message: /Users/fbricon/.m2/repository/io/quarkus/missing/9.9.9/missing-9.9.9.jar does not exist
  Code: -32603

**Comment by angelozerr** [comment]
@fbricon I cannot reproduce it, could you please share your project

**Comment by angelozerr** [comment]
Ok I can reproduce it with https://github.com/FroMage/RivieraDEV-Quarkus

**Comment by fbricon** [comment]
Self-contained project: [quakuus.zip](https://github.com/redhat-developer/quarkus-ls/files/11159204/quakuus.zip)
