### ISSUE TITLE
Qute now support optional end tags for sections 

### ISSUE THREAD

**Issue by ia3andy** [redhat-developer/quarkus-ls#879]
https://github.com/quarkusio/quarkus/pull/33296#event-9223149832

This is only for `let` and `include`

<img width="600" alt="image" src="https://github.com/redhat-developer/intellij-quarkus/assets/2223984/0d4a42ca-eaf4-45c6-bde8-eb945ca69f42">

**Comment by angelozerr** [comment]
> @angelozerr you should be able to move this issue

Done. Thanks for reminding me that i can do this :)

**Comment by ia3andy** [comment]
Thanks @angelozerr
