### ISSUE TITLE
Boolean completion for optional boolean value not working

### ISSUE THREAD

**Issue by xorye** [redhat-developer/quarkus-ls#88]
For Quarkus properties that take a value of `Optional<java.lang.Boolean>`, value completion does not provide `true` and `false` as completion items.

A concrete example to try out is `quarkus.ssl.native`, which expects a value of  `Optional<java.lang.Boolean>`:
![image](https://user-images.githubusercontent.com/20326645/64865125-a2bdb400-d606-11e9-827e-96ac7dfdde0b.png)

**Comment by angelozerr** [comment]
Fixed in https://github.com/redhat-developer/quarkus-ls/pull/94
