### ISSUE TITLE
detected path in plugin are not following renarde paths spec

### ISSUE THREAD

**Issue by ia3andy** [redhat-developer/quarkus-ls#892]
See spec:
https://quarkiverse.io/quarkiverse-docs/quarkus-renarde/dev/index.html#_methods

with 
```java
@Path("/game")
public class GameController extends HxController
```

<img width="632" alt="image" src="https://github.com/redhat-developer/quarkus-ls/assets/2223984/dce8b48d-d847-4c39-8fa9-a0e24a9af0de">

it should be `/game/{id}`

I also find the spec a bit weird but there might be a reason for it cc @fromage

**Comment by fbricon** [comment]
@ia3andy can you check with vscode-quarkus? It might be supported already but some works needs to be ported to intellij

**Comment by fbricon** [comment]
The leading "/" overrides the global path. Try with "{id}", as in 
<img width="206" alt="Screenshot 2023-07-05 at 12 26 22" src="https://github.com/redhat-developer/quarkus-ls/assets/148698/7b2d3ddf-8320-4021-9d7e-a38866ae789e">

**Comment by ia3andy** [comment]
@fbricon look at the spec in Renarde:
<img width="898" alt="image" src="https://github.com/redhat-developer/quarkus-ls/assets/2223984/d295d7b5-a77f-425b-b1e4-b11135e69140">

**Comment by fbricon** [comment]
Yes it's a bug specifically with the Renarde integration:

![Jul-05-2023 12-41-52](https://github.com/redhat-developer/quarkus-ls/assets/148698/fb33d78f-56c6-4f71-8e44-e4d5232af978)
