### ISSUE TITLE
Support customized template path for @CheckedTemplate

### ISSUE THREAD

**Issue by ia3andy** [redhat-developer/quarkus-ls#893]
See IJ PR https://github.com/redhat-developer/intellij-quarkus/pull/1173

<img width="727" alt="image" src="https://github.com/redhat-developer/quarkus-ls/assets/2223984/fbebfece-a1ec-493c-83ab-d39bd64583ca">

should be `templates/game/...`

cc @mkouba can maybe confirm?

**Comment by ia3andy** [comment]
@CheckedTemplate(defaultName = "game") is not working either, I am not sure what is what

**Comment by fbricon** [comment]
https://quarkus.io/guides/qute-reference#customized-template-path is not supported yet

**Comment by mkouba** [comment]
> should be `templates/game/...`
> 
> cc @mkouba can maybe confirm?

Yes.

> `@CheckedTemplate(defaultName = "game")` is not working either, I am not sure what is what

`defaultName` defines the way a template name is extracted from the method name. By default, the element name is taken as-is. The other strategies include "hyphenated element name"; `fooBar()` -> `foo-bar`, and "underscored element name"; `fooBar()` -> `foo_bar`.

**Comment by angelozerr** [comment]
Fixed with https://github.com/redhat-developer/quarkus-ls/pull/972
