### ISSUE TITLE
Support ? in parameter let section

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/quarkus-ls#904]
If you open https://github.com/ia3andy/quarkus-blast/blob/aa969f34616ec63be0268fee20a40097d2ec1ba4/src/main/resources/templates/layout/page.html#L7 you will have an error which says that name is required.

![image](https://github.com/redhat-developer/quarkus-ls/assets/1932211/0b260892-e777-499f-9c38-8fd9881217ca)

It is because the user tag defines name https://github.com/quarkiverse/quarkus-web-bundler/blob/3603361f4db3f6d45f90de8b6667505afc4218af/runtime/src/main/resources/templates/tags/bundleStyle.html#L2

But name is defined here https://github.com/quarkiverse/quarkus-web-bundler/blob/3603361f4db3f6d45f90de8b6667505afc4218af/runtime/src/main/resources/templates/tags/bundleStyle.html#L1 and uses `?`. As we don't support `?` the let parameter is `name?` instead of `name` and in this case we consider that name is a required parameter instead of an optional parameter.

**Comment by datho7561** [comment]
If I create a custom tag:

```html
{#let title?="my cool flexbox"}
<div style="display: flex; gap: 8px; flex-direction: column-reverse;">
    <div>
    1. Qui amet tempor do occaecat elit ullamco ex enim.
    </div>
    <div>
    2. Nisi consequat do occaecat minim proident pariatur qui magna non.
    </div>
    <div>
    3. Proident amet excepteur minim nostrud Lorem enim quis dolore tempor quis.
    </div>
    <div>
        {title}
    </div>
</div>
{/let}
```

then include it in one of the pages, it still complains about `title` being missing.

**Comment by angelozerr** [comment]
Have you tested quarkus blast sample?

**Comment by angelozerr** [comment]
@datho7561 please retry.
