### ISSUE TITLE
 Qute: add arguments metadata for user-defined tags

### ISSUE THREAD

**Issue by ia3andy** [redhat-developer/quarkus-ls#928]
See doc at https://quarkus.io/guides/qute-reference#arguments

https://github.com/quarkusio/quarkus/pull/35818

**Comment by ia3andy** [comment]
cc @angelozerr

**Comment by angelozerr** [comment]
This _args support causes several problem with compeltion and validation.

Given this template usertag `src/main/resources/templates/tags/tag.html`:

`{_args.skip("foo").asHtmlAttributes}`

and a template which use the user tag:

`{#tag foo="dede" /}
`
there is a false positive error:

![image](https://github.com/user-attachments/assets/df6cb785-14f8-4149-ba88-6636d62db6b5)


In other words, when a user tag contains _args, it should have no error with the existing of the parameter.

Other false positive error:

![image](https://github.com/user-attachments/assets/b954e0c0-3b33-4092-b07f-b08d06f90660)**

Completion should show nothing:

![image](https://github.com/user-attachments/assets/d16e139e-e44e-4d15-9d44-7892a1553bef)
