### ISSUE TITLE
java.lang.StackOverflowError when open the file "application.properties"

### ISSUE THREAD

**Issue by ahoehma** [redhat-developer/quarkus-ls#947]
An internal error occurred during: "MicroProfile properties collector". java.lang.StackOverflowError

![image](https://github.com/redhat-developer/quarkus-ls/assets/548214/a614aadd-5c25-452d-8996-4ee6b114204d)

I installed  Quarkus-Tools 1.10.0.v20230622-1450

**Comment by angelozerr** [comment]
Same issue than https://github.com/jbosstools/jbosstools-quarkus/issues/237 which has been fixed. Please wait for @sbouchet create a new release of JBoss Quarkus Tools.

**Comment by ahoehma** [comment]
Ah. Okay. Sorry for the noise!

**Comment by Sharofiddin** [comment]
Is this release published?

**Comment by sbouchet** [comment]
currently on staging area !
