### ISSUE TITLE
Qute: add support for template records

### ISSUE THREAD

**Issue by mkouba** [redhat-developer/quarkus-ls#956]
It's a new (JDK14+) way to define type-safe templates: https://quarkus.io/guides/qute-reference#template-records

**Comment by mkouba** [comment]
Hi @angelozerr, is there any progress? I think that it's quite important.

**Comment by angelozerr** [comment]
@mkouba it is in my scope, but before I'm fixing false positive error that we could have in Qute template that it is very annoying.

I'm working too on https://github.com/redhat-developer/quarkus-ls/issues/876 because @ia3andy need it.

I will try to start something today if I have time.
