### ISSUE TITLE
Qute highlight errors due to formatting 

### ISSUE THREAD

**Issue by gbourant** [redhat-developer/quarkus-ls#966]
The following image is the file `angelozerr.html`. As you can see, based on the formatting it highlights that the code has some errors.

![image](https://github.com/redhat-developer/quarkus-ls/assets/9791051/1287887a-a907-48fd-bb9d-659dd48d2d9a)

To remove the error highlight i did the following, i changed

`ifElementHasError(errorFields, errorKeys)}` with
`ifElementHasError(errorFields,errorKeys) }`, I removed the space after the comma and added a space before the last curly bracket.

`getErrorMessages(errorFields,errorKeys)}` with
`getErrorMessages(errorFields, errorKeys)}` (added a space after the command and added a space before the last curly bracket)

After you fix those two errors you get a new one as shown in the image. So i changed `{errorMessage}` to `{ errorMessage}` (added a space after the first curly bracket)

![image](https://github.com/redhat-developer/quarkus-ls/assets/9791051/ad86913f-2fcd-4e9a-b5fb-a87a339b6f18)

Reproducer: https://github.com/gbourant/qute-bugs

**Comment by fbricon** [comment]
@angelozerr #965 does NOT fix this bug

**Comment by angelozerr** [comment]
@gbourant let me invesitigate your problem.

If you write  `{ errorMessage}` it should be not a valid Qute expression (but perhaps the Qute parser is supporting that now?)

**Comment by angelozerr** [comment]
We have a bug with validationerror of iterable:

![image](https://github.com/redhat-developer/quarkus-ls/assets/1932211/a5b825cc-6b26-4227-99aa-0a56c2d1e78b)

This validation must not be applied for parameter.

**Comment by gbourant** [comment]
> @gbourant another question is the following expression (parameter with space)
> 
> `getErrorMessages(errorFields, errorKeys)`
> 
> is working?

Yes it's working.

**Comment by mkouba** [comment]
> See doc at https://quarkus.pro/guides/qute-reference.html#identifiers

@angelozerr https://quarkus.io/guides/qute-reference#identifiers is the correct link :wink: 

quarkus.pro is :-1:

**Comment by angelozerr** [comment]
@gbourant I have fixed your problem in https://github.com/redhat-developer/quarkus-ls/pull/967
