### ISSUE TITLE
Qute: Cannot locate hyphenated template name

### ISSUE THREAD

**Issue by gbourant** [redhat-developer/quarkus-ls#975]
I changed the `@CheckedTemplate#defaultName` to `CheckedTemplate.HYPHENATED_ELEMENT_NAME` and it shows as an error while the template `verify-phone.html` exists.
 
![image](https://github.com/user-attachments/assets/5a99a5b6-d5ac-4348-a0f0-b6974d6e5d8d)

[Reproducer](https://github.com/gbourant/qute-hyphenated)

**Comment by angelozerr** [comment]
Indeed we don't support this HYPHENATED_ELEMENT_NAME

**Comment by gbourant** [comment]
There are also other options which i did not test. (`UNDERSCORED_ELEMENT_NAME` , `ELEMENT_NAME`)

**Comment by angelozerr** [comment]
Yes I have seen that. Do you know in Qute base code which class does this name file support?

**Comment by gbourant** [comment]
I think `QuteProcessor#defaultedName`

**Comment by angelozerr** [comment]
Thanks, I will try to use https://github.com/quarkusio/quarkus/blob/32392afcd5cbbed86fe119ed90d4c679d4d52123/extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteProcessor.java#L562C5-L578C6
