### ISSUE TITLE
Qute - incorrect behavior for nested template records

### ISSUE THREAD

**Issue by mkouba** [redhat-developer/quarkus-ls#987]
Expected: a template record that is not annotated with `@CheckedTemplate` should be treated as if it was annotated with `@CheckedTemplate` with default values. That is a base path for a nested record should be the simple name of the enclosing class.

Current: IDE expects the base path as if it was a top-level class.

In the following example the template path should be `/src/main/resources/templates/HelloResource/Hello.html`.

![image](https://github.com/user-attachments/assets/6a20c0ca-b082-4675-b875-2b1676de112c)

**Comment by mkouba** [comment]
Also it seems that `@CheckedTemplate` declared on a nested record is not honored:

![image](https://github.com/user-attachments/assets/a8c49269-91b3-474c-81bc-5729bae08a3c)

**Comment by angelozerr** [comment]
Thanks @mkouba for your feedback.

What is the behavior when you definea record outside an inner class?

**Comment by mkouba** [comment]
> Thanks @mkouba for your feedback.
> 
> What is the behavior when you define a record outside an inner class?

It's the same as if you define a top-level class with `@CheckedTemplate` with default values.
